þMLLþMþLLMþMMLKLLMLLþMMþJMKþLLKLJMMLLþJKLLMLþGIJKJJMJJMLJKJMMKMMMþGIKLJIJIKLMMKLKMMLLLMMþ	HJKLMHJKKMMKMMM\KJIMLMþMþIþMMHIJM]MIJ]MLLMLKJLþMM]LJM^MIJKLMMJIMKLKIþ
MMLL\MLMIJKLHJLKJHMLKJIþMþGIKIJKKMMHJLMLHKJMLKJIMMþHJKIIKJKLMIKMMMJLKMMLLMMþMþMGJK]JMLLJKLJML^LKLL_MMLMþMMJHKLJMKMJLMHKLMMKMLMMLKIþMþMLLMMLKJKKMKIKMMKLLMJKMLJIþHIKMKJJLJKMHLMMJKLMIKJLMKJþHIKLKJKKMKM^JMMJKLMLJLMMLMLJþGJKþMMLMMMMMJ^MLMML^MLLLMMLþLþIþLLMMIJLMILMLJIK_MLKIKMMKKþKLMMGGIKLIKJMJKJMIKMLJIKLMIJþJHJKIGIJKMMJLMIKMLIKIMMKJILKKIKIþHJKIJKLMMKMLJKLMKLKMLMLIKJIIþJHKLMLLMMKKLMLKLLLKIHLHHþ
JJMMMKKLLKJHLLMMMKJIþIHKJIMKHKKJKJJKKþJIKIJKIJJKJHþIKJGJJIJþIKJKÿ
þIJLþJKþLLMLLþGJLLIKJþMþMMLLHJKMLJLKLKJþMKJKJIMLLKJLJIþIJLLJMMLKJHMLLKKKJþHKLLIKJJMKKJLMLLMMLJþGJKLMJLKKMMMMLIJMMLþLþ	LLKKLMJLLLLIKJ\LKJMLMLþ	LMMLMKL\JLKMJLKLMMLJLKMLþLMMMMLMMMKKJMLLLM\MMLKKJþMþIJLMJKMLHJ\LIJLMJKLMIJþ	HKLMMKJ\MKGMIKLLIKJMLKJþGJLLMJML^KMKJJK__JLKJMLLJþKKLJKLGILMM_^KM]^MMLMJJMLMLþMLHKLMKHJLMLKLLLKJLJKKKMMMMLþLKGKLLMMLJMLKLL_MJKMKJMMMLLMMþMKJLMKKKMMMKK_KLMKMMMKKJLMMKJþMMMMKIJLMJKMLJJKLMMJKMLJJLMMLþMMKKKMKLLIK^_MKIKKLIKJMLKJMLMþLJMJKJKJLM^_LJKMMJMK^MMMMKKþIMMLIHJMJKJKMML\MM\^MLMJKMLJþGIMMLKJLKMKJIJKMLKJ__IJLIKJMMKþJIKLLKLLKKLMLKIJKMLJKKKLMJLKMKKIþHKKLLMMLMMLLKIMMKKJJKMMLLLKIþJMMMKKMLLMLLKKIMKJMKKJHHþ
JJHJMLKJJKJHJGKLKJJIþIHKIIFJHKFJIJJJKþJIJGJKIGJKJHþIIJGJIGJþIKJKÿ
þKþMMMþJLþJKLLJþKKLLIKJMLKJþKKLLJJKJLKMMMLJKIþKGJLLJMJLLLLMJKLLJIþKHKLMHJJMMLJLIKJK^KJLþJLK]IJLKIM]LJJLKJKLKJþ
Kþ]MJLMLK]MLILL^MLMþLMþ	MþMMKKMLMMMMMKJ_]LKLþMþ	KMKMMGJL]JKMLJ_MJLMIJþ
KGJMMHJLLIKJLMKJLKMIKLþ	IHJM]IJKMIJKK_M]LJMIJKMLþJKJMKMKMMMMKLL^__^LMKMMMLLMþMLLMLKKMIJLMMMMLJHLJKJLKKJMLþMþMMMKIKLLIMMIKKJIMJILKLJþMþKKMHJKMHJKKMKMLJMLLMKMKJþIGLJJKMLJLLLKLKMLMMKMMKLLþIHLKKKMMJ^MMJMMLMMLKJKLKMþIJKMMJLMIK]MIKJJMLMJKLJILþKþMKLMIJLMIJMLKKMMKJLKKILMþMMMKLLMMIKMMMLIMLKLMMLKIHMþJKKMIJKL^IJLMKIJKMMMKJMMLJLKþJHJLMJKLMMMKKK^JJMLMIJKLJLKJKIKIþHKKMMLKJMKMLLKJKLMKLKIMMMJIJþJHJKMLMMLLLKLKMLMMLJLKJHþ
JJHJLLKJKKLLLKLMMLJIþIHKJIIJIKMMKKJKKþJIKIGJIKKJJKþIKHJKJIJþIKJKÿþLLMþMþLLMþLMKþLLMþLLMLLKLMMþLMLLKJLLLMMJLKLLþMþMIJKMMJKJLMJJIIJKJJIþMKJKLMLKLKHJLKIJIJLKJIþ	MþMLMGIKLMIJK\KKKJKMLKJIþLHILMLJKKLMLLMKJKMMþJþ
GKLKMHJMMLMLKML\KLLMMþ
HIKL]IJKLJILKLKMLMLMJMMþMIJKLMJKILMLJIMMKKJIKLJIþMþMKLK\MKLJM^MKJILKJKIIKLJIþMþMLLKLLLK_MLMKLKJLLMJLKKKIþHKLMMLMKMMLKKMLJMKMJLLLJMþHILMKJMLLKLMKIKMKKJKLM^MKMMþJKMLJKIMLKJL]LKIKJLJJK_KJIMþJLMLMMLJLMLKJMMJIIK^KKJKLKJIþLþLMMLLLM^LMMLKKJIM_MMLMMLKJþMMKHIJKLKIJLMLMILJIMMLLKLKþKMLKGILMKILJKJ^JKKLKIIKMMLLJþIKJKLHJKMMIKILMKI^LMMMKJJMLMKKJIþIJKILMLMKLKMLKJLMKMMLLJKKLJIþILKLKLLLKLMLKKMMLLMKLKHHþ
IJMMMKIJJKLLKLMMLKKIþKKIJGJFKKMJKJJKJþHJKJGIIJHKJHþJGIJHJIJþKJJKÿ
þ
KJþLJIþJKIMLKIþLLMLþHILMMJLMKJILLMMþLþGIMMKLLMHIKKKMþLþJKLKLLMIIJLMKJLLJIþJLMMLMJLLJKMJJKILJKIþLMKJMHJLMMMMKKLJMLKJIþKJLMJKL\JKILMML]MLKKLLþMMLLMJLM]LKLJMLLJ\MLMLMMLþMHKKLMM^MLLLMJKKMLMKMMMþLþIJLMKJMLJIL\JJL]KJMLJIþMþJKMKIKILLKIMJKM\JKMMKKIþJLMMJKLJM_KJJMMK^LMJMLKJIþMLMJIMLMM^]MK^_MMLIJLKJMLKþMHJKHKKJLJKLLLKLMLJJKMLKIKMþGIKJJMJKMKJM_L]KLMJLMMLLKIKLþJKJMLHKKMMMKMLK^KKMMMKKKMLJKMþLMMLHJLMKJMMLKJJLMKJMLJIKMKLMþMMJKMMJKILKKIKM_^KILLKMKMMMMþKKMMMM^KMJM\KJLM^MLJKJKJMLLþJLMKJMLM^MMM]LMMKJKJMJKILLMIþKMMJKILJI__JKLMKJIJKMKLJLMMLIþJIKMKLJMLKKKJLMKJIKLMMKKLLKKMKKIþHKLLLKMKJIKLMMIKLLMKMMMLMJKJþJIKJKMIKMKLLKLMLLMLKMMLHþ
JJHKLLKIKKLHKKLMKJJIþIHKKIFJIKFJIKJKKþJIJGJKIGJKJHþIIJIJIGJþIKJKÿþKþJLþKJþLJþMMMþJKþMJKILLKKþJKJLMMMKLJKJJLLKKþHJLLKJLLLLLJMJLLJIKþLJK^^JKILJLMMJJHMLKIKþJKLLM^KJJL]MIKLJI]KLJþ
MLþMMKJILHLM]KLMLJM]þKþMþLþJ]KJKMMMMMLMKKMMþMþ
JHþMLM_KLMKJ]LJIMMKMKþLJHMMLJKMLJKILLKIMMJILþ	LMKJIMJL]M_KKJIMKJI]LJKIþMLLMMMKML^__^LLKMMMMKMKLJKJþLMHKKLJKJLHJLMMMMLJIMKLMMLLMþMþILKLIJMIJKKIMMILLKIKMMNþMþJKMKMLLMJLMKMKKJHMKJHMKKþLLKMMKMMLMKLKLLLJLMKJJLJIþMKLKJKLMMLMMJMM^JMMKKKLJIþLIHLKJMLMJJKIM]KIMLJMLKJIþMLIKKLJKMMKKLMJIMLJIMLKMLLKþMKIKLMMLKLMILMMMKIMMLLKMMMLJþIJKLJLMMJKMMMKJIKMLJI^LKJIMLKKJIþIKKLKJLKJIMLMJJ^KKKMMMLKJMLIþHMMMIKLKMLKJKLLMKMJKLMMKþ
ILJLMMJJKLKLLLMMLMJIþLMLJIKLLLKJKLLKKþIJKMMKKIJKJHþJKIKIJIJþKJJKÿþ¦¨©]þ¥¦¨^þ\]__þ[\]_þ[]^_þ]^^_þ^^__þ\^__þ[^__þ[\^_þ[\^_þ\[^_þZ[]^þ\[\^þ\\\^þ\\]^þ[[^_þ\[\^_þEþ\[Z^_þFþFþGJI\Z\^_JþGþGHIIK[\[^_EJIþFþFþJIJKJ\[\[^_GHJJGþGJIKIJE[[Z\]_IJFJIKJFþ	FJEJJGJKG\\[\]^JJGKJIIGIþJHGJGJFIFKI]\[]^_KEIJJGFIHKJþJHJJIGIKGKGHJG]^G_KIGJFJJGKJJIKIþHKKIKIIFIJKHKLIKJHIKGKIIJJIIþJHJJKJKIFIHKIJIFJGIKHJHHþ
JJHJJJGJJIJHJGHJHJJIþIHKJIIJHKFJIJJKKþJIKIJKIGJKJHþIKJGJIGJþIKJKÿþ¦¨©]þ¥¦¨^þ\]^_þ[[\^þ[\]_þ\]^_þ\^^_þ\]^_þ[]^_þ[\^_þ[\^_þ\\]_þ[]]^þ\\]^þ\\]_þ\\^_þ[]^_þ[]^_þFþJ]\^_GþFþFþGJ[]]^_IþGþFGþHJIJ\\]^_EJIþFþFþGIJJJJF][]]^GHKJGþFþ
GHIIJFKJG][\]^IEJJIGJGþFþFþJIGJFKGJEIZ\\]^KGHKKIIIIGþGJGJKJHGJIKG]\]E^_EIJJJKJKHIJþJIJIKJHGJKEHIG]^G_FGKJHFJIIJKIKIþHKJGJIHFGJKHKFIKGIJKIGIJKJIIþJIKJKGIFJIHGKJIKJGJIHJHHþ
JJHIJGHJJIJHKKHJHKJIþIHKIIFJHKKJKJJKKþJIJGJKIJJKJHþIIJGJJIJþIKJKÿþ¦¨©]þ¥¦¨^þ\]^_þ]\]^þ]]]_þ\]^^þ]\^_þ]]__þ]\__þ]]^_þ[^^_þ\]^_þ[]^^þ\]^^þ\]^_þ\\^_þ[]^_þ]]]_þEþJ[]^_GþFþFþGJIK[[]_IþGþGHIIKJ[Z]_EJIþFþFþJIJKJGJ\[]_GHKJGþFþGJIKIJEIKZ]]_IEJJIGJGþFþFJEJJGJJGK\[]^_KGHKKIIIIGþJHGJGJFIFKIL]E]^_EIJJJKJKHIJþJHJJIGIKGKGHJGLG^_FGKJHFJIIJKIKIþHKKIKIIFIJKHKHLKGIJKIGIJKJIIþJHJJKJKIFIHIKJIKJGJIHJHHþ
JJHJJJGJJIJHKKHJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJIJþIKJKÿþ¦¨©]þ¥¦¨^þ\]^^þ]\]^þ[[]_þ\]^_þ]]^_þ[]^_þZ\^_þ\\__þ\]^_þ[]^_þ[]__þ\^__þ[]^_þZ\^_þ[^^_þ[^^_þFþJ\^^^þFþFþGJ\\^^^JþGþFGþHJIJ\[]^_EJIþFþFþGIJJJJFZ\]^_GHJJGþGHIIJFKJG[\]^_IJFJIKJFþFþJIGJFKGJEI\[\^__KGKJIIGIþGJGJKJHGJIKGL]\]E_KEIJJGFIHKJþJIJIKJHGJKEHIGL]^GLIGJFJJGKJJIKIþHKJGJIHFGJKHKFIHKHIKGKIIJJIIþJIKJKGIFJIHGIJIFJGIKHJHHþ
JJHIJGHJJIJHJGHJHJJIþIHKIIFJHKFJIJJKKþJIJGJKIGJKJHþIIJGJIGJþIKJKÿþ¦¨©]þ¥¦¨^þ\]^]þ[]^_þ\]^_þ]^^_þ]^__þ\]__þ[\^_þ[]^_þ\]^_þ\\^_þ[\]^þ\]]^þ[]]^þZ]^^þ[\^_þ\[^_þFþIK\[^_GþFþGþJIH\\^_IþGþFþIJEKJ\]^_HJIþFþGJJHGJF\\^_^HKJGþFþ
FJKIJFJIEGZ\]^_EJJIGJGþFþIGIIJKGJKG\[]\^_GHKKIIIIGþJKHIFGJJIEJI]E]^__IJJJKJKHIJþIKIJJKGJJFJGIJHG^__GKJHFJIIJKIKIþIIJJIIKGKIHJKIIKGIJKIGIJKJIIþHHJHKIGJFIJIKJIKJGJIHJHHþ
IJJHJHGJHJJHKKHJHKJIþKKJJIJFKKKJKJJKKþHJKJGIIJJKJHþJGIJJJIJþKJJKÿþ¦¨©þ¥¦¨þ^]þ]^^þ]\þ^]]]\]_þ^\^þ^^_[]_]]\]][\]þ]þ[\^_^^þ\þ]\[^^__þ]þ^^þ]]_þ]þ]þ]^_þ\^þ]\\þ^^_þ\^þ]\]^^^]þ]^_^]\\]^þ^]þ\[[^^^^þ^]]]_\[þ^]\^_]\[þ]þ^[^_þ]]\[[]þ\^_þ]\þ\]_þ]þ\[]_þ[[[^þ]þ[\]^_[[þ[\þ]\[\]]þ]^_][[\þ]]]þ[\^^þ\þ[]^þ[þ\^_þ\þ\^__þ\]__þ]]^ÿþ¦¨©þ¥¦¨þ]þ\]^þ]þ[]_þ]_þ^^^^^]þ\^_^^^^]_þ^]þ]^___þ^^]__þ_]]^þ\]^þ]\]þ\\\þ]\]þ[[[\þ\]^þ[]]]þ]þ][[[^þ_þ^]þ]^[\]^þ_þ^]]^_[]^þ_þ___þ\[_þ____þ\\[þ]þ]^^\[[\]þ\^_^]\þ\]_þ^]]þ]]_þ^^]\\^þ^[\^þ\^_þ\^_^þ\]^_þ]]^_ÿþ¦¨©þ¥¦¨þ^]þ\]^þ^_þ^^]^_þ__þ^_þ^]^__^þ__þ\þ[[^___^^þ][þ[\]]_þ]\[[\]^_]_þ[]]]þ_^_þ]þ\[þ^^_þ]^þ[þ]^_^_þ\þ]þ\^__þ\þ[þ]þ]]\þ\]þ[þ]þ\^]\þ\]]\[\þ]þ^]þ[^^]\]^^]]]þ^^^^]þ\^_^^^þ^][]_þ[[]_þ_þ[þ[]^^^þ___þ\þ[]^_]^þ^_þ\[\]þ_[_^_þ\þ[\^_þ[þ[]]^þ\]þ\\\]\\]^þ\]^_^^_þ\^_^þ]]^_ÿþ¦¨©þ¥¦¨þ]þ\]^þ]^^^þ[]_þ]^^þ_^þ\^_þ\]^þ_^]^_þ\]^]^þ[þ	]þ_[__]]^þ]^]]\þ\þ[\]_]^þ^\\[\[[\]^_^þ^_\___þ_^_þ\^þ]^_þ]\^þ\]_þ^þ[þ]]_^_þ\þ^^þ\^__þ[^þ\þ^[^_þ[þ\^þ\þ\\]þ\þ[^þ]þ\\[[\\\\_þ]þ[]]\\_^^þ]þ\[^___þ\þ^]þ\[[]^þ]\\[[[^_]^_þ^þ]^^^^þ^_^^_þ[___þ\^__þ\^_^þ\]_^þ]]^_ÿþ¦¨©þ¥¦¨þ\]^þ^][]_þ^\^_^_þ]þ^]^__þ]þ]þ]__þ]]]]þ]þ\]_þ]^^^\þ]þ
]þ]þ]^_]]^þ]\\þ]^^^]þ^][]^þ^]þ][[^þ^]\]\[þ\]þ^]]_\[[]^þ]þ[^__^^þ\þ[\__þ^\\[\[[\_^_þ^þ^_\___þ^]_^_þ\þ\^þ^]__þ\þ]\^þ^^\\þ\]þ\]\[[\\]^þ_þ\[]^^^^^]þ___þ[\^_þ]þ_^þ[]_þ_^\^_^þ\\_^þ\]_^þ]]^_ÿþ¦¨þ¥¦þ]_þ]þ_^þ\_þ^þ]^þ__^\__^^^]þ_^[^]]þ\[[þ[\þ]]][þ]_þ^[[[_þ^]\_þ]þ^]_þ]þ]^þ^þ]þ\\þ^]þ\^þ[þ^]þ[]þ\þ^]þ\[þ]þ_þ][þ^]þ\[^]þ]^þ_þ^\þ[þ^^]\_^]]^þ_þ^[þ\þ_]]þ___þ_þ_\\\\[[__þ____þ^^_\\]_^þ___^_þ\[^þ[\_þ[\_þ\]_þ[]^ÿþ¦¨þ¥¦þ]_þ\_þ]þ\_þ^þ]\\þ\][^þ]^__þ^^\\^_[^_^þ^^þ[\]__^^þ^þ[\_]^þ__^þ[\^^_\^þ[^^þ^_þ^þ]^þ]þ^[]þ\þ_\[\þ\\þ^]_[\\\_^þ[\þ___^\þ\þ[]þ^\]þ\[þ[\\þ\[[\]_]þ]þ]]þ___þ]__þ]]^þ\^]^^þZ^^þ[^_þ[]_þ\[_þ\]^ÿþ¦¨þ¥¦þ]_þ^]þ\^þ^[þ_^\^þ\þ[þ^][]]^_þ^[þ\þ][\^^þ_\\\\[[]_þ^^_\\]__þ]þ_____þ]þ^þ^^_þ]þ]þ]^þ^þ]^þ]þ[^_^^^]^þ]þ[^^]]]þ]þ]þ]þ[[_þ]þ]þ]]þ[\[þ\þ
]þ_\_____]\[[\[\\^þ__þ^^[^^^_[\þ___\_^þ__þ_[þ\[[\þ^\þ_[[\___þ^\]þ[___]__þ\[[\_þ_\^_þ^__þ_\^_þ[^_þ[]_þ\]_þ\]^ÿþ¦¨þ¥¦þ]_þ^þ\_þ^^]þ\^þ^__^þ^]\þ\]^_þ[þ^]^]\]^þ\]]^]þ^]^_þ^_]þ]þ_\[þ\þ]þ^_\[[\[\\^þ\þ]^þ___\_^þ]þ]þ[^þ^\þ]\[\\þ\^þ^\]þ]]\]][]þ^^[\þ\[þ]\þ]þ_þ^[]^]þ]^þ_þ]\þ[\__^]]^þ_þ^][[\______þ_þ^^__^_þ____þ\^_þ[^_þ\]_þ\]_þ\]^ÿþ¦¨þ¥¦þ]^þ\]þ^^]þ]\\þ^þ_þ__^]\[]\]]^þ____þ_^][]^þ^þ_[\^þ^þ[\]þ\^__þ\þ]þ^^^^_^_þ\þ^þ_]^þ\þ^þ[^þ\]^þ\^þ]]þ^]]þ[]þ]]^^]þ^^][[]]^þ]]þ^\[^^þ\\þ\][]\þ^^\\^_[[]þ^^þ[\\_]þ\]þ[\þ]\[\]þ[\^^þ]]\]þ[^^þ]_^þ^þ[^_þ[]_þZ]_þ\]^ÿþLKLþKJILKLMþKJIKLþKJIKLKJLKLMþKJKJIKJLþKJILKJKLKLKLMþKJIKLLLMLMNMNþKJKLJLMKNMKJKLMNþJILKLMKMLKLMJKLLMþKJLMLMMKLLJLMMLLMNþJKLMMJKMMMIJKMNJKLMNþKJILKKKJILJKLLMKJKMþLKJLMMKKJLMMMJKLLLMNþKJLLMKKJKLMLMNLJMMKMþ
LKLLKMKKLLMLLLLKJKLMLKLNþ	LKKJLLMLMMLMJKMLJKMLMMþLJKKJILKMMIJKLJJKLJKKLNþJILKJILKJLMJKLLJKLLLLMLþ
KJLMKJKLMKLMMNLLMMKMLKLþJKIKKLLMKJLLJLMLMLNLLKLMNþKLMKKLLMLKKMIJKMNMMLLMLKLLNþMKLIJKMLMMJKLLLLNLJKLMLMþKKLKJKLMKJMLKMMKMMLJJKLLLMNþLKLLKJILKMJJKMLLJLKKLKMMMNNþLLLMMKJKJILKMLMLKKLLLMNNþJKLMKJKLMMKJLLMLLLMLMLMNþKLLLMKJKLLMMMLMMMMMNþLþKLLMMMþNMMNþMþNþLþMþNNþNþMþNÿþKþKJKþKJIJKLMþKJLMLþKJKKJKLMNþKJKLKLMLLMLþLJKMLLMLMKLMNþJKJKLLNMKLKKLMþJKLLJMMJLLJKLLLNþLKJKMKJKKLMMLMMMNþJILKJKMLIJKLMLLMMNþKJLMIJJKLLLLMMLLMþJKLMMMKLKMMJKKLMKKLMNþ
KLLMJKKLMLJIJKLMKJKMþLIJKLLLIJKLLLJKLMLMMþ
KJJKLMMLJKLLLMMLMMLMMNNþLJKLKKLMMMNMJKLLMMNþKJILMMMNMKNLJKJKLLNþKJKLMKJKLKLMJKLLKJKKLMNþ
KLMLLKJKLLMLLMKLJLMþKKJIKJKIJMMMJKLKLJKKLMLþ
MLLJKJKLLMLKLMLMLMLMMMNþ
LMKLLLMJIMMLJJKLLLMNNþMMLMLMLKJJLMKLLMLMMþMþMLKMKLMLMNMNMNNþKLþLMNMNþMþNþMþNMþNþNþNÿþIþJKþIKLþJKþJLMMþLJKKMMLMþJILKLJILJLLMNþKJLMKJKJKMþKJKKJILJKLLLMNþKLKIMMKJLLMMKMMMNþMLKKJKLMMMLLJKMþMKJILLMMKMLLKLJKLMþKJIKLLLMKJILKKJKKLMMMNþJLLMKJILKJLLJKLMKKLþKJKLMMMMKJKLJKLMLLKLþKLLLKMNKKLLMKKLMLKMLMLMþ
MKJMLKJILKKMLMNMJMNMMMNþ
MLMJLMKJLLMKMJMKLMKKLMNþKJIJKLKJKLMMLLLJKKJLKLþKLLLKLLLMMKLJKLLLKMLLLMþKLKLMLMMKMJILLLMKLMKMKMNMþ	LKLJILLMKKJJKLKLKJNLNþLMLKJLKJJKLLMMLMLMMþMKJLJKKIKJKLMMLLLMLMþLKLLJKLKLLLKKLMLMMLNNMþ
MþLLMLMMMLMMLMNMNþNþLMMþMNþMNNMMþNMþLMþNþN_þNþNþ]_ÿþKþKMþJLMþIKLLMþKIJLKJKþKJLJKLLMþKJILKLLKLMLþKJLMMLKLKMNNþKJKLMMLKJKLMþKKJILKLJKLLKLMMMþLKJLMLMMMMMMLLMNNþ
KJILKJKLMMMJKMLMLJKMþKJLJKJKKJKKLMLKLMLMNþ
KJKLIJIJKIJJLKJIKLMLMMNþKJILKJKJKLJKMMKLMKLKMMMþ
LLJKLJLMMLMLLKKLJJKLMLLMNþKJKLLMLLKLMLMLLJJKKLLLKMþKLLKKMKMKMJMKLMKJKLLKLMLLMNþKJMLKJLMKJKMJILKMMJKMMKLþKLLMJKJILJKMMKJKLKMLMLMMMMNþLLMKLLLMKJLMLJKLLLLMKLMLMþ	KJILKJKLMMMLJMMLMLLKMKLMNþLKJLMLMMLLKLKMMMLMLKLMþ	KJKLMKJILKIKJKMMMMKMLKLMþKLLþMMLLKJLJKLLLMKLKLMLMMNþLþMMKJLKMLMMLMLMLLLMMþMKLLþLMþL_NþMNMMþNþLþMþ]_þNÿþLþLKJLþJKMLþLKJKLMNþJIKMLMNþKJIKKLLKLMMNþKJIKKJKLLþJIKJJIJJKKKLMMMNþLJKKJKLLKLMLLMþKJIKLLLKLKJKKLMNLMNþKJKKMLKJKKJKKLMLMNþKJKKJKLKIJKKJKLJKLþKLLKJLLIJKLKLLMLLMMLNþ
KLIKLKLKKKLKJKKLMMLMLMNþKJKLKJLLKIKLJJLKKLMMþ
KJLJIKJKJIJKLLKJJKLKLLMNþKLLMLKJILKLKKMLLKKJLJKLþKKJKKLLMLJKKLLMKKLLKLMþKKLJIKLKKLMKKLJKKLMMLMMMNþLJKJLMLLKKLLLLMLMLKJLMþ	KJKLKKJLMLLMMKMMMLMLKLMNþKLLJKJJLMKLMLJKLLMKKJLKLMNþ	LKLKMMLKLKKJKLKJLKLMNþ
KJLKLLLKKLLLKLKJKLLLMMNþKLMMKLLMLKMMMMMLKMNMMMNNNþMMþMLþ^NMNMLMþNMNþMþMþ]_NþNMNþNþ\_þNÿþKJþKJILKJMLJKþKLJLLKKMLKLKþKJKKLMLLKKIJLMþKJILLJLMKJKLJKKLKþKJJKLMKJLKLMLMKJþJJLLKLKMLKKLMLKKJKþLKKLMLMKJLMLKLMMLþLKLMMLMLMLJKLLKLKJþLMJJKLKJKLMLIJKLLMLþLLKLMLKJIKLLKKLKJKþKKJKMLLMMKLIJKLJIKLþKLLLLLKMKJKJKLKMLKLKþLMLMMKLMKLMMLKMMLJþKLJMLMLLKLMLLMJKLKKþLLMJLLMMLJILKLMLLþLLKJLKJIKLKLLJKMMMLþLMMLKKJKMLKKLLMNMþLMNMKLLKLMMLLMMNþNþNþMþLMMþNþMþNþNþNÿþJKLþKLLLMJILMþLKIJKLNMKJLNþKJIKJKLMMKJKLMNNþLKLLMMLKLLNMKLNþMLKJLKJIJKKKJILMLMNþKLKJIJKJLMMLKJLKLMþLMLKJKLMMKJIJKJIKLþKJKKLKLMNLLLJJLMKJLþMLLJLLKJIJKKJKLMMMLMþKJKLMLKJKLMLMNMLMNMþLKLMLKJKLMNMLMJKLMLþLMLKLKLLKMNMLIJKJLKMþMKJMLIJKLMLJKLLKJMKþMJIJKKJKLMLKMNLLMKþNMKJLKIJKLLJIJMMLKLþMLKMLKLMLJIJKMKKLMþMMLKLMLJKJKLKLMLMþMLLMMLJKLLLMMMMþMþNþLMMLMNNMþNMþNÿþKLJKþKJILKþKLMLJKMKKJLLþKLJIKJKLLKJKLMMKþLLKJILKJILMKJILKþKLKKLLKJLMLKKLLLJLMþKJLMLJKMLKMMMLMMLKLMMþKKMLMNMLMKLLKMMKMKKþKJILMNMKLMNMKJLNLLKMLþ
KLMLJKMLKMMKLKLMMMJLMKþNMLLLKLLKKLMMNJLLKLJþLKJKLKKLJKLMKLKMLJLþ
KJKJIKLKJILKLKMKJKLKJKþLLKLKJIKLMLLKJILMJLMþKJLLMKLLLMMMLLKJKLKKMþ
KLKMMKLKJKLLKLKJKJILJKþLKJKLLLMMKJKJLMLKKKLþJKLLKLMKLLKJLKLJJJLKþJKLMMMMKJIKJIJJKLKKLNþMMLMKLLKLLJKLJKLLNþLKLKJLMMLJJKLKLLKþNþKLMMKLLKLNMLþMLþMþKLMþLNþNMþNþMþMþNÿþKJKLKþKJILKLKJLMþKJIKJKKJLMNþKJIJKJLKLMKKLMMNþKJKLKJLMNMKLLLMNþLKJIJILMLKMLMLMNMMLMþJKLKJKMLIJKLNMLKJKþKJLLMMKLMJKKLMMJKKLMþJKLKKJLKMLKMMLLIJKLMLþ
LKLKJIJKLMNLKKMJKLLMMKþJLJKLLMKJKLLLLLMNMLJþKLMLMNMKJKLJKKLMNMLJKþ
KLMMKKLMLMMIJKLMMLMLKJþMLKJKLLMJKLLLLMKKLMKþLLKJIKKLLKLMNMKJIJKLMþMLKKJLMKJKLMKJKJKLJKþKJKLMLKJIJMLKJKKLKJþKLMMMLKJKJKLKIKIJKLKþKLMLKJKJKLKJKLJKLMLþMMLKLLLKLKLMKLMMMþMLþMLNþMNLMNþNþNþNMþNNþNþNþNÿþLKJþLLKMMKLJILKþLKKMJJKMMKKLJLMNþKJKILLMNJILLKLMMMNþJKKLLJLMJMKJLMKJILNþJLLMLLMMMKJILKMNKJMNþKLMMMMMMKKLMKJLMKJILMþLMLMJIJKLKJILKMMMNKJLþ
KMLJIJKJLLKLKJLMNLJKLMþ
LLKLJJLMMJKJKKJILMJILLþ	KJIKJKLMNLJKKLMNKJLLMJKþKLLKJIJKMKLMNMKLLKLMLþ	KJKLMMMJJLKLMLMLMNMMKLMþKLLLMMKJKLMMLIJKLNMLKJIMþLþKMKLLKMNNJKKLMMJKKLMJþ
KLLKMJKKLJKMMLLIJKLJKLþ	KLLKLIJKLMLJKKMJKLLLLLMþ
KJLJKLLLLIJKLLMMMNKLKLþ	KLMMLMMNKJKLJKKLMKMLJKMþ	LþMKKJMLLLIJKLMNLMLKJKþMLKJKLJLJKLLLLMKKLMJKþMKJILKLKLLMNMKJIJKLMMþMLKKJLMKJLKMKJKJKKLMMþKJKLMMKJIKMLKJKKLMMLþLLþMMKLKKLLKIJKLMMLMþMþMKLKJLLMJKLLLLMMNþMLKLLMMMLLMMþMNMNþLþNMþMNMþNþNþNÿþMLKJþKJILKLMLJKLMNþKLLLMKKMLJKMNþKJKKLMLMKJKLMNþJIKLLJLMKJLLKJKLMNþKIJKLLKJLKLLLMKLMþKLIJKJKMLKMLMLKKJKMþKJMKKKLLJKMKJILKJLMLLþMLKLMMLLJKLKKJLLMKJKþKLKLJIKJKLLKJKLMMKMKLþ
KLMNMLKJILKJILMKJILKLKþKLKKLLKJKLLKKKLLJLMLþ
KJLMLJIKLKLMMLLMLKLMLKþLKJMLKLMLMKLLKNMKMLKJþ
KJLLMNMKLMMLJILMLLLMLKþ	KLKIJKLKKMMLKKLMMMJKMKLþMMLLKJLLKKLMNMJKLKLJLþLKJIKJMLIJLMKLLMLJLKþ	KJKKLLMMMKJKLKMKJKLMLKMþLLKLMKJIKLMLKJILKJLMLþKMLMKLLLKMNMMKKJKKLMKþ
KJMMIKKLMLLKLMNLKIKJKLþ	KLLKJKLLMNMKJJKLJJKLJLMþLKLMLMKJILKIJKKKLKMNþMþLMNJKLKJKKJKLLLNþMþKLMMJKLLKLMMNþLþLKLþMLþNþLþMÿ
þKJKLMþJKLþLKJLKJIJLKLLKþJKLMKJLMKJKJIþKKLMLLKLKJKLLKþLKJLKLKLMMLMLMMLþIKLJLMKMLMLKJLMþJKJKLMMMLKJILKMNþKLLLMLLKMMLKJLMMþKLMKMLKJILKJKLMMNþIJLKJILKKLLKMNLLþKJLLMLMKJLLMNMMLMMþJKLKJKLMMLLMNNMNþKLMKLKLMMNNMNNMNMþLLKLMNKLLMNNNMNNMþMLMLLLMNNMNMMNMNþKþLNNNNMMNNþNþNþNÿ
þLKJþJIKþLþLKMMLKJIKLMJKþLKLMLKLLMNMJþLKJKMLKJKLMMLMKLþMNMNMKJKKLMKLMþMLMLKMMKJKLLMMLKJþKJKMMKLLMMNMLKIKþMLJILKKLMNMLLKKJJLþLKJLMMMLLKKLJKLMþKJLKJKLLKJJJKKLMMþLKLLMMLKJLKMJMLLMLMþLMMLKJKLKMMKLMLMMNþMJKLLLLMMLKJMMLNNþMLKLKJILMLKLLKLMMMþLMKJIKMLIJKLMNNNMþMMLKKLKIJKLMLMMNNþKLMMLKLLLLMMNMþLþNLþMMþMNNþNþMþNþNÿ	þKLþKLKJþMKþLKLIJLIJMLKMLMþLKKMLMLKJLKJLLMLþLKJKMLMKLLNMMKþLKJKLMNKJLLMMKLJþLKJKJKJILKLLLMKJLJKþLKJILLKJLMKKMJLMKLþLLMKJKLMMMLIJKLLMþKJIKLLLNMKLLJKLLMMKþLKJKJKLKLNNMMMKKKLþKJLLMMIJLNKMLJJLLLKþKLLKMKJKLNMLIJKKLMMMþMLKLLLMMKLKLLLKMLMþKLKLMMNLLNMLLMMMLþKLMLKLMLKNMKMMNNMNþLþMMMKJLMLLKLMMNNþKJKLMJLMKLMMMNþKLLLMIJKLLMNNNMþLþLJKLLMNNMNNNþLMMMþMNNþNþNþNÿ	þLKJIþJKJKLþLKJIKJKJIKLLKMþKMLKKLKJKKIKMLKþKJILLKJILKLMLJKMMKMþLKILKLKJLMLMLKLKMNþLKJKJKLMKJKMLMMNJþKKKJKKLLJKMLLJKMNNMNþKLLLMMLLMKJKLJKMNMMþKMKILKLKJILMLMKKJJMNNþLMKJLKMLKLLMJKLLMNMNþKJLLMMKKJMKLLMMNKNMMþKLKKKJKLIJKLKLJKMKLMNþMLMMKLJKLLLLNKLMMLNNþKLKJKLNMMJMMNKLLMMNþLKLLINMKMLJMMLMMNMNþMLLLKLMMLMKLKJKLLMNMþLKJIMKMLMKLLMLMMNNþMMILJLMMNLMNMMNNNþKLþLMNMþMNþMNþLþMNþNþMþNþNÿþLþKLLKJþKþLKJLKJMKJKIJKþLLKLKJILKLKJLLþLKJLMLKKJLMMKLMþKLKLMMNMLKLMMLLKLþKLMLJILKKLMMNMLMKLMþKLKLMJLMJMLMLKLLMNþLLJLKKLLMMLKIJLKMNNþKKLJKLLKIKLKJIJLMLLNNþLKMLMKJLMNLKLLMNKMMMþKLKKLLMKJILKMLMLNNNþLKJKLMNMLMMKJLMMKLMNMþLKLMLKMLKJKLKJMLKMNLþIJMIKMLKLLMMMMLKMNNNþJKLJILKKLMNMLLKKJJLMNþKLMLKJLMMNMLKKLJKLMLNþLKJKKJILKJJIJKKLMMLMþKLLNMMKJLKMJMLLMLMMNþLMMNKJKLKMNKLMLMMNMNþMMIKLLLMMNLKJMMLNNNMþMKLLKJIMKMKLLKLMMMNMþLMMNIKMLIJKLMNNNNNNþMMNKJKLIJKLMLMMNNNþKLLþJKLLLLMMNNNþLMþLþMMþMNNNþMþMþNþNÿþIJKþJKLþLKþLKLKLLMLKJKIKLþLKJKKLKJIJJKMþMLKLKJLKJKKJIJKþMLKJLKIJIJKIJKJKLþLMJKLLKKJJKLLMLþJIKIJKIKLKLJLMNNþMLKJJKLLKIKJKLMNMNþKIJKLMLMKLLLMMLMMþMKLKLMMKJLLMMLLMNNþLKKJKJILKLLLMKJLKLMNþJLLLKJLMKKMJLKJMMNþLKMKJKLMMMLIJKLMKNNþLKIJLLLMKLLJKLLMLLMNþLKKJILKLMNMMMKJKMMNþLMMKJLMKMLJJLLLNNMþLKMKJKLMMLIJKKLMMMNNþKLLLLMKLKLLLKMLMMNþKLKLMMNLLNMLLMMMLLNþKLLþKLMLKNMKMMNNMNMMþMMKJLMLLKLMMNNMNþKJKLMJLMKLMMMNNNþKLLþMIJKLLMNNNMNþLþJKLLMNNMNNNþLMMMþMNNþNþNþNÿþLþMLþKLKKLMMþLJKLLKLJKKLMMMþKLKLKLMLJLMLMLMNþKLLLMJKLKMLKKJLþLKKILKJILKKJIKKLþMIJKKMLKJLMLKLJKMþKKKLLKJKLMLMLMLMNNþKLLLKLLLKKLLKMMLMþLMMKLMKKLKJKMLLJKLþKLMLMJKLMLKMKJIKMþNMLKKLMMKJLMJKKLLMMþKJILLJIJKLMLMLMKMNþMLKJKLKLMMLKLKLMLþLMLKLKLKLLKJKLMLMNþMLKLMLLKJKMLMMNMþLLMMMLMLMMMLMLMNþMMþNMNþNMþNMNMLNNþNþNþNþNþNÿþJKJKKLMþKLKIJKJKKJKLMþLKJKLIJKLLLMþKKLMLKJIJKKLKLMMNþLMKJILMKKLMJJKLMþMLJIKLLMLMMMLMLLMMMþLLKLLLKJMKJLKNMKLNþMLJIKJIKLMKJLMKLKKLMþKJLLJLMJKJKLMLKJLMNþLLMLMMLKLLKMLJLMJLMþKJLKLMJLMJKJJLKLMKLLþLKJKMJKJIKLMKJLMLKMNþMLKLMKKJKLKKJKLKLLMþNMLKJKJILKLLLKJLLKLMþMKJIJKLKJLMKJKLKLLMþLMKLJKJKLMKLKLMLMMþJKLMLKJLLMJKLLMLLNNþKLMNMLKLMLKLMMMNNþMMNþNMLMNMLMNMþNþNMMþNMþNþNþNÿþJKþKLMþIJKLMMLLLMMþJKLLJKMLKMMKLMNþLKMIJKLJLLKJKMþKJILKKJIKKKLKLKKLMNþJKLKJLMJKJLMMLKLMNMþJIMLKKLKKLMMLKLMLMLþKKJLMKJLMKJKLJLKJLMNþJLLMMMLMKJKLMKMLKKLMNþLMMLLLMNLLJKLLKLMKKLþMLMKJKJKKLMLKLMNLLMKLþNKLLLIJKLKKMLMLMMKMMLNþ
JLKLKKLKJLLMMLKJLJLLþKKJIKJMLKLMLLLJKLKLKLþMMIKJIJMLMMLJLKLKIKLLNþ
MLKKIJKLMNLKKJLMNKMNþKMLJKKLLJLLMLLMNMLLMNþMMLJKJKJIKMLKMLKJKJLþNLKLKJLKLLKJLKJMLKþNLMLKLLMKJLMLKMMLNþMNMLMMNMLMNMMNMNþNþNMþNþNMþNMNþNþNþNÿþMLLþLMþKLMþNMLJKLLKLJKLLMþNMLLKKLMKJIKLMMþMLKKLLMMLKLMMLKLKLMþLKLLKMLLKLKMLKJLLMþJJKLJKKLKLKJMLKKLLMMþKKLMLIJKLMJKLLLLKMLMNþJLKMKJKLMMLKKLMMMLKKþKKLKKLLKKLMLKJKLMLLMMþKLKLMKKJIKLMLKKJLKKLMMþ
KMLMMMLLKJLLKJLLKMLKNþLKKLLLKJKLJKKIKKLMKMþJMLKKKLLLIJKJKKLMKJLþLLMLKJLKJKLJKLLLLMJKMþMMLKJKKLMKLLKLKKKLKLMNþ
MLKJIKLMLKJKLKJIJKLKþKIJKKLLLKJKLLKIKKJKLNþLKIKJILKJKLJKLKLLKLLMNþ
MMJKKJJKLKMLKLLLMLMMþMMKLKLKLMMNMLMNMþMNMNþMLLMMNLNþNMNþNþNþNMMþNþNþNÿþLþLþLKKLMMþMMLMNMLJKKLMþMLKJKMLMMJLMLKLMMþMKLKJKJKLKLLKJKLþLKKLILKJILKJJKJKLMþKJIKKJLMKJLMLKLMKLMþKIKJKLKKLMMLMKMLMMKþJKLLLKJJKLKKLJKLNMMKþLJKLKJKLLMKJIKLMKKLMMþKJIKKLLLNMLKLNMLKLMKLMNþ	LKKJLLJMMLKLKMLKJLMLMþKLLLKLKJILKLKJMLKKLMLMMþ	LILKLLLMKJLMJKLLLLKKMLMNþLKKLKMKJKLMMMLKLMMKJKLþ
JLLKLKKLKMMKLLKJKLMLLMMþ	LKMKKLMLLKILKLMKKJLKMþLKLMLMNMMMKJLMLJLLKMLLMNþKLLKMMJLKJKLJLKJKKLMLMþ
LKJMNLKKLLLIJKJKKLMKJLMþ	JKLLMKJLLKJKLJKLLLLMKMþ
LLMMKJKKKLLMJKLLJKKLMLMþ	NMKJLKJKLMNIJKLKJKLLLMNNþ	NMLIKJILKJKLLJKKLLMMNNþKMLLMKJLLKMMLKLMMMNþNþ
MMLLKJKLMMMNMMLNMþMNþNþMMLþMNLNþNMNþNþNþNþNþNÿþ	MLKLMþLMLþLLKJKKMNþMLJLKIJKIJKLþLKIJKJKLJKLJKKLMNNþMJJKLJKKLMLIKKLLMNþLKKLLKKLMLJKLLKKLMþKLLKJKJKKLMLKJKLJKMNþKLLMJKKLMKLJLKJKLMLþMMKIJKLMMLMLJLKLKLKMNþLIJKLLJLKKLMIKLMMLMLMNþ
KJLKLIJKLJKJKJKMLJKKMþKKJILKKJILKKLKLLMLJLLNþ
JKLJKLMJKJLMMLKLMMLKLMþ
JILKJKLKKLMMLKLMLMLMMMNþ	KKJLMKJLMKJKLJLKLKMMMþJLLMMMLMKJKLMLMKKLMLLMþ
LMMMLKMMLLIJLLKLMMLKMMNþ	MLMJKLKJKLMLKMLMLKJKLLMþ	MKLLLIJJKKLMLLKMMLKJLMþ
JLKLJKLKJLMMMMMJLKLLKLMþ	KMJIKJMLKMMKLMJKLMKJLMMMþMLIKJIJMLMLLKJKLKKLLMNþ
LKKLKLIJJKMLKKLJKLMNþNþ
LMLLLKJLKLLMLLKKMMNþMþMNMLKLMMNMMMLMNþNþNþNMLMþNþNMþNMNþMMNþNþNþNÿ
þMLKJþMLMþLKLLKLKJKLKLþKMMMLJLKLMLMLMþMLKMMLKLMNMLKþJKLLMNMMLKJKLLMþMLKKLMLMKMLJKLþNMMLKJKLMMLLKMMþMMLKJKLMKLNMLKLMNþNMMLKJKLJJKLMLKMþLLMMMLLKKLJKLKJKMþMMLNNMMLLMKLKMLMþNMNNMLMMMLLJKLKLMþMNMNNMNNMMLMLMMMLNþNNMNNNMLMMNNMLNMþNNNþNMMNþNMþNþNþNþNþNÿ
þNMLKþMNþNNMMLJKLKLMNþMMLLMMLJJKLKLMþMLKNLLMMLMNMNþLKLMKKLKJKMMKLMNþKJKLLMMLLLKLMKMþLKLLKLLMNMLKLLKMþMLKLKJKLMNMMLJLLMNþMMLKJKLKJKLKJKLJKþMLMLLMLMKLJLMLKKLMþNMMLMLKNMKLKJKLJLLMþNNLMNJKLNMMLLLMKLMþMMMLKLLKMJMKMMLLMNþNNNNMLKJLKKMLLMMNþNNMMLMLKKLLMMLþNþNNNMMLLLLMMþNMþNNNMþMMþMþNþNþMþNþNÿ	KþKLMNþMLKLMLKJKLMþMMLKJKILLMþMLMLLLKMLNMMNþNMLMMLLJKMMLMLMNþNLMLKMLLLKLJKMLKLNþNNMMLLKKMLJKLKMMNþMLNMMMLMMMLKJKMKLþNMNNKKJLLKMNLLKLLMNþMNLMMLMNMLKLJJKJKLþMNMLJJLMKMLJKMMKLKMþNNMLKKJJLLNLKJKJKLMNþMLMKLLLKLKMMLLLKLMþLMNMLLMNLLNMMMMLMþNMNNMMKMNKLMLKLMMMþNNMMLKLLMLJKMMLNþNþNMMMLKMLJMLKJMNMþMNNNMLLKJLMMNMMþNNNMNNMLLMMMþNþNþNNMMMMMNþNþMþNþNÿ	þJKLMþJKLþMMLKKMMMLKKLNMMþKLNMLJKJKLMJKLMþJLLMJIKLLKLIJKLLMMNþLKJKMLKJLKKLKJLKLMþKLKMMKLMMLKLKLJKKLNþLKMMLLJLMMNMMLKJJKLNþMMLLKJKKJKMLLMLLLKMþLLKKJIJLMMNLJKLKKJMNþKKLLMLKJLMLKLMLLJKLMNþMMMKLMMLMLKJJKMMLKJKþMMLKMKKLKMLJKLKJKLLMþNNLMMLKLMLKKLJLKNMNMNþNMMLLKLMMKLMMLKJKLKMMNþ
NMNMKLMMLKMKMLJLLKMþMNMLMLKKLLMLMMLKLLLMþNNMMNMLLKMLMKMKJKMMþNNNNMNMLNMMLJKJMNþNMþNMþMNMLKMLNþNþNþNþNMþNþNÿþKLþKLKJþLþMKJMLMMLMMKþMLKLKLMLJKLKMLKMþLKJMLKJMKLMLLMLþMJKMMNLLLMNMMKLMNþMKJJKMMLMLKJKLMNþNMKJLJKMMKMLJKLLMMþMLMLKLMLKJKLMLJKLþNMMMLKJKILLMMLKLMLþMLMLKLLMKMLLNMLKMNNþMKLMLLMLLJKMMLKMNNþNMKJLJKMMMLKLJKLMNNþMMKIKLJMKKMLJKLKLMNNþMNJLLKJILMMMLKJKMKLþLLKLMLKKJLLKMNLLKLLMNþMLKJIKMMMNMLKLJJKJKLþMMKLLLJJLMKMLJKMMKLMþMNMMMLKKJJLMMLKJKMMNMþNMMLMKLLLKLKMMLLLKMNþNLLMMMLLMNLLNMMMKLMþMMNMNNMMKMNKLMLKLMNþNMNNMMLKLLMLKJMMLNNNþNNNMMMLKMLJMLKLMNNþNMNNNMLLKJLMþNMMþNNNMNNMLLNMþNþNNMþMNþNþNþNÿþJKLþLKþKLMLMLKþMþLKKLIJKMLKMMLMLþKJIJLKIJKLKLKLMMþJLJKKIKLLMJKMLMþLKLKJKLLIJKJKKLLNþMLMLKJIJKLLMLMLKLNþMKLMMLKKLKMLKLKLMþNLMMLKLMMLLKMMLKMNNþNMLKMLKKLNMLMKLLNMþNMMLNMLJKJKMLJKLMMNþMNNLLMJIKLLKLIJKKLMþNNMKJKMLKJMLKKLLLMLLþMNNLKMMKLMNMLLKMJKLMLþNNMKLMLLJLLMMMLLKLMþNMMLMKKJLKJKMLLMLMNLþNMLMKJIJILMNLJJKMKMNþMLKKLLLLKJLMLKLMKLJMNþLLMMMKNMMLMLKJJKMMLLþLMMMLKMKKLKMLJKLKJKLþMMNNLMMLKMLLKLKJLKMLþMNNMMLLKMMMKLMLKKJLMNþNMNMNMKLMMLJLLMLJLMþNMMNMLMLKKLKMNMLLKLKþNNNMMNMLLKMLMKMKMMLþNþNNMþMLNþMLJMþNþNþNMþMþNÿþLMþ¦¨þIJKLM¥¦LKþLMþKLKJJL\]MLJKLMMNþKJLKLKIJKM[\MMKJKLþKLKJLKKLMLLZ\]MLKJKKLMNNþKJLKIJIJLKLKKL]^LKIJLLLMNþLMJKLKKKLLKJJKL^MJKLJKKLMþLKJILJLLKLLJLKIJKLMLIJJLJKLLþKJLKJKLJJKILMMMLLKKJKKJKLMKþJMKJKLLKLJKMMKMLKLLLJKLKJKJLMþLMKJLLMKJKLJJKLKMLLKJKLKLKMMKLMþMKJJMMLMKLKKJJKKIMMKLLKLMLMNMLNþJLMþLMMLMþKLMMLKJLLKMLMNMLþNMNþLMþMMþMþLMþLMLKMKKLMþNMþMþMþMþMþML_LMLMMNþNþM^_þNþNþM^^þ^]^þ]]^þEþJ[]]IþFþFþGJIKZ]^IJþGþGHIIKJY\^JEJIþFþFþJIJKJGKZ\^KGHJJGþGJIKIJEIKZ\]^IJFJIKJFþ	FJEJJGJKGKL[\]^KJGKJIIGIþJHGJGJFIFKIJK]E^_JEIJJGFIHKJþJHJJIGIKGKGHJGJ^GHKIGJFJJGKJJIKIþHKKIKIIFIJKHKJIKJHIKGKIIJJIIþJHJJKJKIFIHIIJIFJGIKHJHHþ
JJHJJJGJJIJHJGHJHJJIþIHKJIIJHKFJIJJKKþJIKIJKIGJKJHþIKJGJIGJþIKJKÿþ
MMLKþLMLþKLMþMMLKLMLK¦¨MJLNLKLMMNþLKIJLMM¥¦LKLLKJKLþLLIKJJKMMK\]MLKJJKJLMNþMMLIKLLKJKMLKLLKLMLKLMLMMNþLKJKLMLKLMMLKKLMLMLMLMMMMNþLLLLLMNMLMKJIKMMMNNLKLJMLMNþLKJILKMKLMMKLLLJJLMKNLJKLMþLMþLKJKLKMMKMMMLKKJJLMNLKJLMþMþKJLIJJLLKLKLMKLLLKLKMMLKKLMþKLLKLMKJMLKKMMMLLMNLLNMMMMKLMþLþLMLMMKJKLKNNMMKMNKLMLþNMþNþMLKKLLKKLLLMLKLKMLJKMþNþKLLKLMNMMNMMKLKMKJMLKLMþ	LþLMNþNNMNNLKLMMKLMþNþNþNNNMMMNNMMNþ^MNNþNNþ]N_þ\__þ[]_þFþJZ]_þGþFþFþGJE[]_IIþGþFGþHJIJGZ\^JEJIþFþFþGIJJJJFZ[Z^JGHKJGþFþ
GHIIJFKJG\[]_EIEJJIGJGþFþFþJIGJFKGJEI]\]_GKGHKKIIIIGþGJGJKJHGJIKGK^]__IEIJJJKJKHIJþJIJIKJHGJKEHIGK_GHFGKJHFJIIJKIKIþHKJGJIHFGJKHKFIKGIJKIGIJKJIIþJIKJKGIFJIHGKJIKJGJIHJHHþ
JJHIJGHJJIJHKKHJHKJIþIHKIIFJHKKJKJJKKþJIJGJKIJJKJHþIIJGJJIJþIKJKÿþLþKþLMNþJKKLþ¦¨IKJKMþJIKLLJLM¥¦KLKLKMNþKLKIJKLMN\]MMLLKKLMþIKLJIJKLKMM[\MLKLMLMKNþ
KJLJKMLMLMLMMKKJLKKKKMMþJJLKLLKJMLLLIJJKLMKLMKJMMNþLLJIKJKLJLJKLKLMMLNLLMLKLþJIKKJILKLKLLMLMMLKMMKMMLKMþKLKJLKKJLMKJLKLLKMMJLKLLKLMLþKLKLLIJILMMKJIKJILMJKLMKJKMLNþKJIJKLKKLLJKKLLKJJKLKKLLMLNþKLMKLNMLKKJKJLLMLLKLJKLMMMNþLþLNþNMLLKLLMMNMMLKKMMMNþNþMþNþLþNM_NNMLMNLNNþ]N_þNMMNNMþ\]^þNþNþNþ\[^þ[]^þ\]^þEþJZ\_þGþFþFþGJIKZ[_IIþGþGHIIKJ[Z^JEJIþFþFþJIJKJGJ\[^KGHKJGþFþGJIKIJEIK\]_EIEJJIGJGþFþFJEJJGJJGK]\]_GKGHKKIIIIGþJHGJGJFIFKIL_E^_IEIJJJKJKHIJþJHJJIGIKGKGHJGLG_HFGKJHFJIIJKIKIþHKKIKIIFIJKHKIIKGIJKIGIJKJIIþJHJJKJKIFIHIKJIKJGJIHJHHþ
JJHJJJGJJIJHKKHJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJIJþIKJKÿþKJþKJILþLKLJ¦¨þLKMþKKJMMLKL¥¦LKJKKMNþKJKLLMLMM\]MKLKLKMþJIKLLJLMKJKL[\MMLLKJKMLþ
KLKJIKJMLIKLLMLKMLKJJKLþKKJLLMMMKJIJKLLKJKMMKLMLMþKIJKKLMKJKLKIJJLKIJKIJKLMLþKJKLLMKLLLMLJKKLLKKJJKLMKJLKþLMLþMMIKKLMLKILKKKKJKLLLLMKJLMþMþLJKLMMLMKJKLLLJKKLJKKLMLMMMþKMKLMLMLKJKLMMLKKLKJKLLMMNþNþLLMþLMNLMKJLKKKLLJKKLLMMNþMþMþLMþMMJLLKMMLKLMMMNþMLMMNNMMLNMþMNþMNNþNMNþNþNþN__þNþ^^^þ]]^þ\[]þFþJ\[^IþFþFþGJEZ\]IJþGþFGþHJIJGZ[]JEJIþFþFþGIJJJJFH\[]EGHJJGþGHIIJFKJGI\\^GIJFJIKJFþFþJIGJFKGJEIK[]_^IJGKJIIGIþGJGJKJHGJIKGKL]_E_JEIJJGFIHKJþJIJIKJHGJKEHIGK__GHIGJFJJGKJJIKIþHKJGJIHFGJKHKFIIKHIKGKIIJJIIþJIKJKGIFJIHGIJIFJGIKHJHHþ
JJHIJGHJJIJHJGHJHJJIþIHKIIFJHKFJIJJKKþJIJGJKIGJKJHþIIJGJIGJþIKJKÿþ
IJMþKLLKLþMLMþKLJILMJJKM¦¨KJKLKþLLKJIJLML¥¦IKLMLKMLþKLKJKIKLIJN\]KLMNMLKLMþKJLMLJIKLMLMNM^NMLKJKLMLLMþKJMLMIKLMLMMMLMKMLJKLJKLMþKJLLMLMMLLMKLMLLLKLKJMMLLJLLMþKLLIJKLLJKLJKKLMLKLMLKMKJKKMþLþKLLMJLLIJKLKKMLMKJLMJKLLLMþKJLJIKLJKLKKLMMMJKLMLMLMMMNþKLMKJKLILJMLKMMKLLMMMKLKLMNþLþLKLNMKJIJMLMLLKKLMKJKLLMNþLNþNLKLKJJKMLKKJKMLLMNMþ	MþMLLKLKLLMLMLMNMMNþNþMMMLMMMNMMþNMþNMþNMNþNNNþNþNþNþ^_Nþ]^_þ\^_þ[]^þFþIKZ]^þGþFþGþJIE[\]_IþGþFþIJEJGZ[\_EJIþFþGJJHGJI[\\_GHKJGþFþ
FJKIJFJIE[\\]_IEJJIGJGþFþIGIIJKGJIG]^]^_KGHKKIIIIGþJKHIFGJJIEJI^E^^_EIJJJKJKHIJþIKIJJKGJJFJGIJHG__FGKJHFJIIJKIKIþIIJJIIKGKIHJKIIKGIJKIGIJKJIIþHHJHKIGJFIJIKJIKJGJIHJHHþ
IJJHJHGJHJJHKKHJHKJIþKKJJIJFKKKJKJJKKþHJKJGIIJJKJHþJGIJJJIJþKJJKÿþKþKJþLJKMþKKLMþKJKMLMþKLKMLKMþKJKJJLMþLLIJKLMNMþLJKKLLMNLNþLMKJKMLþLKLMKJKLMMNþMMLKMMMNþLMNþMþMþ]_þLKLNMLMN\_MþNMþLKJILKKLM]_LMKLMþMþKJJKJKLM_KMLJKMLLMNþ
KJILKKJIJKL_MKLJJKJKLþ
NLMKJJIKKLJKMNMJKMMKLLMþ	LKJKKKJKJJKJLMLKKJKLMMMMþKLKJLJKLLKKJLKMLKLKMþNþKLMNKMLKJKLLKJKKMLMLLMþ
LMþLNLLKKLKLKJKLLKMNMMþ	MþLLKMNLMMLKMMMNþNþMLNMML_NMþNMþMþN]_þNþNþ\_þ[_ÿþIþJKþIKLþJLMMþLKKMMLMþJILJLLMNþLMKJKJKMþLKILJKLLLMNþKJLLMMKMMMþLLKKMMLMLNþMMKLLMNþ^_þJIKLþ]_MþLKLMNþKLJKL\_KLLKLMþIKLLJKLM[_LKMJKKLMþKKIJKLLMN]^KLKMIJKJMþKJIJKJKLLLMMLMLMLKJKLMþ	KLJKKKLJMMKLMKLMLNLIKMNþ	LKLLMLKKJKLKNMMLKLKJLMþ	MMþMJKLLKLLLMLMKJKMLLLþJKKLMLLKKKLJKLLMMNMNNþ
KLþLMMNMLKLMLMNMMNþNþLLþNNMN_NMþNMþNþ]_þNþNþ\_þ[_ÿþJþKJKþJIJKLMþKJLMþKJIKMKLMNþLLMLKMLþKJMNLMLMMMþKJKLMMLMKþMJKLLJKLLþMKJMMLLþ^MLþKJILMþ]_þKLþKKJLM\_LKLMLMNþKJKLMN[_KLMNMþJIKLLJKLM]_MMLKJKLMNþKKJKLLKLMMLMKMLJKLþJKJLMLMMLKLLKLMNMLKJKþKLJKLMNLKLMMMNKLLMMKLMþ	KLKLMKLMLKLMKKLJJKLMLKNMþKLLJMKMMKJLMLLLKKLKLKMLþNþLþLLLKJKLKJKMKLMMLMMLMþMþKLLLKJKLLLMNMLMNMLMþLþKLLMMNNMNNMþNþMþLþM_MNNþNNþ\_þNþNþ[_ÿþKþKMþJLMþIKLLMþKIJLKJLþKJLJKLMþJILKLLKLMLþKJKMMLJKKMþIKKMMLKJKLMþKJILKLJKLLMNþLKJKMLMMMNþKLJKKLLNþLM_þLþ^^þLKKLLMþLLLJK\_LMIJKLþKLJIKJKLL\_MJKLJKKLþLLKJILKJ^_LMKIJKJKLþKLKKLKKJLMLLKLJLKJKLKLMþKJLMLJKLLIMKJKJKLIJKLKLKMþ	KJMLMLKJKLKLKLKJIJKKLJKþKJLLMMLKJKLKLKJKJKKKIJMMMLþKLLIJKLKLKJKIJKLJKLKLKJLþNMþLþLLKLKLLIJIJKLKLMLMKMþNþLJJKLKLKLMMMMNNMLþKJLKLNMLNMLMMMNþNMþKLMþLNþNMNNMNNNNþNþMþN_þNþNþ\_þ[_ÿþKþLMLþLKLMþLKIJLLMþLJKJLNþLKJKKJKLMNþLLKMKLMLþLJKLMLJKKMNþKLLLKKJKLMþKMMMKLLMMNþLMKLKLLMNþLLMNþKLLþL]^þKJKLLþMLKLJILKM\^KLMLMMKMþKMLLKJLL\_MMLKJKLþMLLKJKLMM\_LMKMLJKLþMLLKKLLLMML]_KLLMLLKJLMþLKIJLMMLKLKLLLMLJKLKJKLLMþKJLMMKJIJKJKJLLKKJJLKMMLNþMLLMKLMKLMKIIKKKLMKKKJKþMJLLMMLJIJKJKJLLMLJLLKMþLLKJIKLKLLJLKLKMLMMLKLLNþMþMNKLKMLKLLMKMLMKMKJKþKJLLLMMLLM^LNMMLJKMLþKLLþLMþLþMþ]MþMNMLMNMþLþMþNþ\NþNþNMþNþ[_þNþ[_ÿþ^þ
]þ\]_þ]\þ[]_þ_þ\_þ\^þ[[þ[\[þ[\]þ\[^þZ[]^þ]\þ\]]þ]\^þ[[^þ\[\þ\[ZþJJ\Z]^JþHJIJ[\]XJJþJXJWJ\\][^_JHJJJþHJXWWJY[[Z]_KJJJJKJþ
JKYWJXYYZ\][^_[ZYXJYIJIþJHJJZXYZYZ[][^\[YWXGJIHKJþJHJJJGYKXY[[Z\^^_\[YXHWXXYJJIKIþHKJIJYWXXYYZ[[[[[YWXYXYJJJIIþJHJJYXWWJYZZZYYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþþ
^þ\]^þ[\^þ[\[^þ
\_þ
\þ]þ[]_þ[]^_þ[\^þ\\þ[]þ\
]þ\]þ
\^þ[]^þ[]þJ]\_þJJ[]]^_JþHJIJ\
^_XJJþJXJWJH][]]^JHJJJþHJXWWJXY[
^KJJJJKJþ
JKYWJXYYZ[Z\\]^XYYXJYIJIþJHJJZXYZYZ\[\
]]ZYWWXGJIHKJþJHJJJGYKXY[[[\[Z\[[ZYHWXXYJJIKIþHKJIJYWXXYY[\[[[ZZWXYXYJJJIIþJHJJYXWWJY[ZZYYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþ]þ
^þ
]^þ][]þ[
_þ]^þ\^þ\þ]\_þ]]^þ[þ
þ[þ\^þ
^þ\\^þ[^_þ]]þJ[þJJK[[]JþHJIJJ[Z_XJJþJXJWJHW\[]JHJJJþHJXWWJXX[Z]_KJJJJKJþ
JKYWJXYYZ[
[[ZYXJYIJIþJHJJZXYZYZ[\\]_\[ZWXGJIHKJþJHJJJGYKXY[[Z[\
\^\[ZXHWXXYJJIKIþHKJIJYWXXYYXZ[\[ZZWXYXYJJJIIþJHJJYXWWJYXZZYYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþ]þ
þ\]^þ
þ[\þ\[þ]
[þ[\þZ\^^þ
\_þ\^_þ[^þZ]þ\^_þ[]^þZ\_þ[^_þ^þJ\^^þJJ
\^^JþHJIJ
[XJJþJXJWJHZ\]_JHJJJþHJXWWJXZ[
_KJJJJKJþ
JKYWJXYYZ[\[\[YXJYIJIþJHJJZXYZZZ[\[[
\ZZYXGJIHKJþJHJJJGYKXY[[Z[\\[\[YXHWXXYJJIKIþHKJIJYWXXYYZ[\\[[ZWXYXYJJJIIþJHJJYXWWJYZZZZYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþ]þ
þ\]^]þ]\^þ]\^þ]^^_þ^]^þ\]þ[
^þ[_þ\]^þ

^þ[
]^þ
]þ[]þZ]^þ[\^_þ
[_þJ\[þJJK\
^JþHJIJJ
]^_YJJþJXJWJHY
\^_HJJJþHJXWWJXY[Z
KKJJKJþ
JKYWJXYYYZ\[]
^ZYXJYIJIþJHJJZXYZYZ[\[Z]][ZYXGJIHKJþJHJJJGYKXY[[Z[\[^\ZXHWXXYJJIKIþHKJIJYWXXYYX[\\\[ZWXYXYJJJIIþJHJJYXWWJYXZ[YYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþþ
þþ^þþ^^
_þ\
þ_[]_]
]]]þ]þ[\^þ\þ][[^_þ]þ^þ]_þþþ]þ\þ\
þ^_þ\^þ]
^^]þ]^_\\]^þ^]þ\[[^^þ]]_\[þ^
\\þ]þ[^þ
[[þ
^þ]\þ
]þ]þ^[þ[\[^þ]þ[
^_[[þ[\þ]\[
]þ^][[
þ]]þ[\^þ\þ[]þ[þ
^_þ\þ
^þ\þÿþþ
þ]þ\^þþ[]þ]_þ^]þ\^^]_þþ]__þ^^þ_]þ\^þ]
þ\\\þ\]þ[[[\þ\^þ[]]þ]þ[[[^þ^]þ[\]þ_þ_[]^þ_þ_þ
[^þ_þ
\[þ]þ]^\[[
þ\^^
þ\]_þ^]þ]þ]\\þ^[\þ
þ
þ\þ]^ÿþþ
þþ\]^þ^_þ]^_þ_þþ_^þ_þ\þ[\__^^þ][þ\
]þ]
[\
]^_þ[]]þþ]þ\[þ^þ]^þ\þ]^þ\þ]þ\_þ[þ[þ]þ
[þ[]þ[þþ\
\[þ[[
[[
þ]þ^þ[_
[\]]]þ^]þ\^þ][]_þ\\]_þ_þ[þ\]^^þ_þ\þ[]^_^þ^_þ
[
]þ[^_þ
þ[\^þ[þ[]þ\þ\[\\[[\þ
\\__þ\]þ]^_ÿþþ
þþ\]^þ^þ[_þ]^^þ_^þ
þ\^þ]þ\]^]þ[þ	þ[_]þ]^]þ\þ[
þ\
[\[[\]^_^þ^_
þ^_þ
þþ\þ\]þ^þ[þ]_^þ\þ^þ
_þ[^þ\þ^\_þ\þ\þ\þ
\]þ]þ[þ]þ\
]]\\
\þþ[

_^^þþ\\_þ\þ^]þ\[[]^þ]\\[]]^]_þ^þ]^þ_^^þ[_þ\_þ\^þ\]_þ]^ÿþþ
þ
]^þ^][^þ^
þ]þ_þþ]þ]þ]]þ]þ\]þ]^^^[þ[þ
]þ]þ]^_]^þ[\\þ]^]þ^[]^þ_^þ[[^þ
\[þ
þ^]_
[[]þþ\^__^þ\þ\
_þ^
\[\[\\^þ^þ^_
__þ^]_^þ
þ
þ^__þ[þ\^þ
\þ[þ\]\[\\[[þ_þ
[]^^
\þ_þ[
^_þ
þ^þ[_þ^\^_^þ
\_þ\^þ]ÿþþ
þ]^þ]þþ\þ^þþ_][_^^^þ[^]þ\[[þ[þ]]][þ]þ[
[þ]þþ^]þ]þ]^þþþ\\þ^]þ
þ[þ^þ[þ\þ^þ
[þ]þ_þ[þ^]þ\[]þ]þ_þ^\þ[þ^^\_^]þ_þ[þ
þ_]]þ_þþ_\\
\[[__þ_þ^\\_þ_þ\[þ[\þ[
_þ\_þ[ÿþþ
þ]^þ]þþ\þþ]\[þ[þ^^_þ^^[\^_[^þ[\þ^þ[
_^þ__þ[\^\þ[^þ^þþ]^þ]þ[]þþ_
[\þ\þ^[\
\^þ[\þ\þ
þ[þ^[þ
[þ[
\þ\[[\_]þþ]þ_þ]_þ]^þ\]^þZ^þ[^þ[þ
[þ\]^ÿþþ
þ]_þ^þ\þ^[þ_\_þ\þ[þ[]
þ[þ\þ][\^^þ_\
\\[\]_þ^_
\]þ]þ___þ]þþ^^þ]þ]þ]^þ^þ]^þþ[^^]^þ]þ[^^]þ]þ]þþ\[_þ]þþ]þ\\[þ\þ
þ_\__]
[[
[\
þ__þ^[^\\þ__\þ__þ_[þ\\[\þ^
þ[[\_þ\þ[___]_þ\[[\_þ_\þ_þ_\_þ[þ[]þ
_þ
ÿþþ
þ^_þ^þ\^þ^þ\þ^^þ^
þ][^þ[þ^]
[
þ\]þ]_þ_[þþ\[þ\þ]þ^_
[\\[
\^þ\þ]þ
_^þ]þ]þ[^þ^\þ\[
þ
þ^
]þ]
][þ^\
þ\\þ
þ]þ_þ^[]]þ^þ_þ\þ[\_]þ_þ^[[\____þþ^^__^_þ____þ
þ[þ
]_þ
_þ\]^ÿþþ
þ]_þ\[þ_þ^þ\[þ\þ_þ^_
\
_^þ____þ][\^þ^þ_[
þ^þ\þ[\þ^\
[\^_þ]þ]þ^_þþþ_]þ]þ]þ[þ]þ\þ]]þ^]þ\]þ]^^þ^^]\[]^þ]]þ^
\^þ\
þ\[
þ^
\[[þ^þ[\
]þþ[
þ[[^þ[\^þ]\^þ[^^þ]_^þþ[_þ[þZ]_þ\^ÿþ^þ^þ]þ]þ\þ
þ[^þ]þ\^þþ^þþ^þþ]þþ]þ]
[[

]þ\þ]þ
þþ^^[þ]þ^þ^þþþ\þ[þ]^þ\[\__]þ__^^þ]^þ]þ\þ
þ[þ]\þ[ÿ	þþ]þ
þ
þ^þ[^þ_þ\þ_þ[þ__þ\^þ_
_þ^þ^_\_þ\þ__þ^\\\[
þ[__þ[^þ]þ\þ\þ
[þþ^\\[\[[
þþ^_
__þþ\þ_þþ\þ
\þ\
[þ\^^\[þ[_þ^[\þ[_ÿþ]þ^þ]þ]þ^þ\_þ
_þ^þ\þ^^[^þ^\þ]þ]
þ\
^þ]þ^þ^][\\^þþ]þ^þþ]þ__^^]^þ
^]]þ[]þ[^þþ\_þ^]þ]þþ^þþ_]\þ]þ__þ_[
þ^þ\þ__^\[[\
þ
þ^þ[þ
þ\_ÿþ^þþ]^þþ^þ^þ\_þ^^þ_]^þ
_þ_]^^[_þ_
^þ[þ]þ_
^þþ
þ\þþ^þ\þ_[_þ^þ^\\þ\\þ^þ[þ_\
[
þþ
þ\^_[]^þ\þ]\^þ_\^þ[þ\^þþ\þ[^þ\\

\þ\\^þ]þ]
þ\
_þ^][\\_þ^_þ[þ[_ÿþ^þ^þ]þ]^þ\_þþ
þ^þ\þ[þ\^þ[þ[^þ\þ]^þþ[þ]þ]þ]þ][]\\þ\\þþ
_\
^^þ\[þ^þþ[]\þ^\
]\þ__þ^þ^[^þ]\þ[
]^þ^[\
__^þ^_\^]^þ
]^þ\þ[_þ\ÿþþ
þ_þ^þ]^þ_þþ\]þþ_þ\^þþ^þ[^þ]^^_þ_þ\]^_þþ_þ\^þþ_]^_þþ_^þþ]^_^]þþ\]þ]^_þ[þþ\þ_þ]]þ\^_þ[]þ]þ^þJ^]þJJK]]IJþHJIJJ^^WXJJþJXJWJHW]]_ZJHJJJþHJXWWJXXZ\]^_KJJJJKJþ
JKYWJXYYYZ[\]^_ZYXXJYIJIþJHJJZXYZYZ[[\]^^_[ZYWXGJIHKJþJHJJJGYKXY[[ZZ\___[YYXHWXXYJJIKIþHKJIJYWXXYYXY[[[ZZWXYXYJJJIIþJHJJYXWWJYXZ[ZYYXGWKHJHHþ
JJHJJHWXYYZYKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþþ^þ
þ_^þ_þ^_^]_^þ_þþ^_^þ_þ^þþþ\]_þ_þ^]_^]þ_þ]_þ]^þ_þ^_þþ_þ]þ_þ^þ]^þ[_þ\_þ]_þ\_þ[^þ[^þJ]KþJJK]IJþHJIJJ\^XYJJþJXJWJH[]YJHJJJþHJXWWJYZ[^ZKJJJJKJþ
JKYWJXYYZ[\\_[ZYYXJYIJIþJHJJZXYZYZ[\_^_[ZZXWXGJIHKJþJHJJJGYKXY[[ZZ\__\ZYXXHWXXYJJIKIþHKJIJYWXXYYXYZ\ZZZWXYXYJJJIIþJHJJYXWWJYXZZYYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþ^þþ^þ_^þ
þ^þ_^_^__þ_]_^þ]^þ^^þ]^_]þ_^þ]^_þþ__^þ_þ]þþ^þþþ_þ]^þþ]þ^þ^þ
_þ]_þ]_þ]^_þ\]þJ_þJJK\]_IJþHJIJJ]^_YXJJþJXJWJHY^_XJHJJJþHJXWWJXYZ\]YKJJJJKJþ
JKYWJXYYYZ\]_ZYXYXJYIJIþJHJJZXYZYZ[\[]^[ZZYWXGJIHKJþJHJJJGYKXY[[Z[\^_\ZYXXHWXXYJJIKIþHKJIJYWXXYYZ[\[ZZZWXYXYJJJIIþJHJJYXWWJYZ[ZYYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþþþ
þþ]^þþ\]þþþ_þ\^þþþ_^\]_þ_]]þ]^þ_þ^___^_þ_þ^þþþ_þ_þ
^þ^þþ\_þ^þ]þþ^þ]_þ[^þ[þ\^þ[^þJþJJK[^^IJþHJIJJ\YXJJþJXJWJHW
]_ZJHJJJþHJXWWJXXZZ^_[KJJJJKJþ
JKYWJXYYYZ[^_[YXXJYIJIþJHJJZXYZYZ[\]\]^_\ZYWXGJIHKJþJHJJJGYKXY[[ZZ\]__\[YXHWXXYJJIKIþHKJIJYWXXYYXY\\\ZZWXYXYJJJIIþJHJJYXWWJYXZZYYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþþ^þ
þ^þ^þ]^þ^_þ___^\]^_þ_]\^_þ^^þ]þ]^_þ]^_^]þ^þþ__^]þ_þ]__þ_þþ\^þþþþ\_þ]_þ]_þ[]_þ[\þ\^þJ]^þJJK^JþHJIJJ]]^_XJJþJXJWJHZ[]^JHJJJþHJXWWJXYZ[]KJJJJKJþ
JKYWJXYYYZ\[]]ZYYXJYIJIþJHJJZXYZYZ[\^\]]^[ZWWXGJIHKJþJHJJJGYKXY[[Z[\^^^[ZXXHWXXYJJIKIþHKJIJYWXXYYX[[\[ZZWXYXYJJJIIþJHJJYXWWJYXZZYYYXGWKHJHHþ
JJHJJHWXYYYZKJHWHJJIþIHKJIYXWXYWKJJKKþJIJIYXWXXYJHþIKJGJJGJþIKJKÿþ]þ^þ^þ\þ]þþþ_þþ_^þ]__^_þ_þ_\_þþ_þ^þþ_þþþ^þþ_þ^þ__þ__þ^]___þ^]__þ_^þ__þ_þ]_þ_þþ]_þþ_þ^_þ^þ^þ]þ]^ÿþþ^þ[þ\^þ]þ\þþþ[þþ_þ[þ__þ_]]_þ_\þ]_þ]þ]þ]_þ]þþþ^þ_þ_^^^]þþ^þ^]þ_þþ^þþ[]þ_þþ^_]\_þ_þ^_þ]^þþþ^þÿþþþ]_þ\þþþ\þ_þ^þ_þ
_þ[þ\þ]_þ]þ_þ^þþ_þþ^þ__þ]þþ_þ]þþþ_\þþþ^þ^_þ^þ^þ]]_þþ^^þ]_þ_^^þ_þ^þ^þ^^ÿþþþ^þþ]_þ^þ\þþ^þ[þ^þ
þ^[þ\þ]_þ]þþ^þ^þ]^þþ^^þ[þ^þþþ\þþ^^þ^]þ^]þ^þ^þþ^]þ^^^]þ]]^[]^þ^\þ^þþþ]þ]^ÿþ^þþþ]^þþ]þ^þ\þþ^þ]þ^_þ_\^þ_\_þ[þ[_þ[þ\þ\þþ]þ^þ\þ__^þ^þ^þ_þ_þ_þþ]]_þþþ^[]þþ\þ^þ]þþ]þ]^ÿ