þJJJJþJJKJKHIJþJJIJJIJJJJKJþJHJJJHJJIHJJHIJIþHJIKIHJJKHJIJKJJJJKJþ
JJIJJJJJJHJKJJHIJHKJIIJIþJHKJJJHJHKIJJIHJJJJJJJHJIHKJþJHJJJIHKJJJJJHJJJIJKIJHJJIKJJIKIþHKJJJIHJIHKJKJJKJHJKIKIJJJIHþIHJJKJJIJIHKIJIIJIJIHJIHþ
IJHJJJHJJIJHJJIJHJJIþIHKJIIJHJKJHJJKJþJIJIJKIJJKJHþIKJIJJHJþIKJKÿþKJKKþKJLKLHJKþHKJKJKJKKJKKþHKLKJHKJKHJKHIKJþKJJKJHKKLHLKKLJKJKLKþ
KLJHKLKJKHKJKJHJKHLKJJKJþKHIKKJHJHLIKKLHKJKLJKKHKJHLKþKHKKKIHLJKIHKJHKKIKLIKHLKJLKKJLJþHLIKKJKHJKLHLJKLKHKLJKJKKLJHþKHJKLKKJKJKLHKJJKJKLHKJHþ
KKHKIKHKKJKJKHJKHKKIþJHLHJLJHJLKLKKLJþKJKJKLIJKJHJþJKKHKKJKþJLKLÿþFþGþEþJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGþFþGJIKIJEIKFJIEIEJJIGJGþFþFJEJJGJJGKJGJKGKGHKKIIIIGþJHGJGJFIFKIJJIEJIEIJJJKJKHIJþJHJJIGIKGKGHJGJKGHFGKJHFJIIJKIKIþHKKIKIIFIJKHKJIKGIJKIGIJKJIIþJHJJKJKIFIHIKJIKJGJIHJHHþ
JJHJJJGJJIJHKKHJHKJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJIJþIKJKÿþFþGFþFþJIGKIþFþFþGJEJIHIJþGþFGþHJIJGJJKJEJIþFþFþGIJJJJFIEJFJGHJJGþGHIIJFKJGKGJGEIJFJIKJFþFþJIGJFKGJEIJIJIGIJGKJIIGIþGJGJKJHGJIKGJJKEJIJEIJJGFIHKJþJIJIKJHGJKEHIGJJGHJIGJFJJGKJJIKIþHKJGJIHFGJKHKFIKJHIKGKIIJJIIþJIKJKGIFJIHGIJIFJGIKHJHHþ
JJHIJGHJJIJHJGHJHJJIþIHKIIFJHKFJIJJKKþJIJGJKIGJKJHþIIJGJIGJþIKJKÿþIþHþFþHþEþFIþGEIþFþGþFþIþIFKIFHGHIFIþHþIþGþJþGGJGIKIGHFJþIþFþ	JþJKILIHKHJLJGIJIHJGJþHþEþFþEþKJKFIKIILIKGJEJKHIKGKþIþFþGþFIFKLGIKIJJJLHKFJJGJEHIIJþGIþHIHJGLFHILIKFKLILGKJHJFIJEKIHJFHIJIKHMGJEMKLGKMJLJIFGHGJIFLJIIGIJIJKHLHJFKJMHJIKMKJGHJHHIGLILJIJKIKLIJIIGLIKKJJLJIKHIKIIKHIJMKKLMJLKJIHJHIJILKHMKJHIFLJILIKKLLLþKLLKJIJIGKJHLJKLKFKGIKJMJLLMþMLKJKJHLKGLJLIJGLHJLKLKMþ
MLMKIHLFMIIJKHIJKMLMþMLJILGKIJKLJJKLMþKJMHLJKIMKKLþLJKKLJLLþLLMKÿþFþIþEþHþGþFþFHIþGþIHþEþHþGFIHGHGIKFIþFþGþKþIþHFHGIKIGJGIþGþHþJGJHIJIGJLJHKHILIKJþJþHþIþKGKIHKJEJGKILIIKIFKJKþEþGIþJIIHEJGJJFKHLJJJIKIGLKJIFIþKHJIKEJIFJHJKGLILKFKILIHFLFJGJþGLIKJLFIJGHGGIJLJMKGLKMEJGMGKHIJHLJLILGIHHJHGJKMKIJHMJKFJHJHKJJKIKKMJIHKIIIEHKIJLJJKLILGIIHIJKKLKLLLKKILIJJFIHJKMHKLKJIHJHIJKLLMLþMLLJMJKIGKJKLKJLKJKJIJIJKLMMþMKLKLJHLKJILJLJKHKJKJKLMþ
MLMKJMLKJIIMGLILKMLLþMLKJJLKJIKHMJLLMþLKKMIKJLIMKMþLLJLKKJLþKMLLÿþEþ EGþGFþHþEFGþEþGEGFþGþGEþEþHþFGGHHHþFGþEGþGFIJEHIIGFþEþGFþGHIFGHJEGJIFGHþGEþEþJFGHHGJJGFJHHGJHþFGþEGIHGFJJGHJIJJFGJHJIGFþ	GFJHHJGHHJHJKHGFJJGGJJFGHþJIJFGIJHIKEJJKHJGHHIJHHGIIKIþJIJHGFIKJKJIJEGJIJHKIEHJJHJIJHKJþIKJJJJIIHJGFKJHKJGEKJKIJJJJHþJIJJKJJJJIFGIHIIFGJKIJIIþ
JJIJJJHGFIJIGFIJIJJJþJIKJJJJIKKJFGHKKþJJJJJKJJJKJIþJKJHJJHJþJKJKÿþEþGEþHþFGþEþGFEþEGþGþKFGEGþGFþHHHGGFJJHþEþEþFGJJHEIJFGJHGEþEGþHGFHJGEJHGFJHGJFGþGFJKHHGHHJFGGKGHHGFIJHþEþIJFGJKHJGFIJKJHGGJFGHGGEþJKHGFGJGGJJFGHKJHIHHGHHHJFGJþHJIJIJGHHHJHHGHHJJGEHJHJKGFJJJHJþIIJJHIKHELHHKJJGEJJHIHIJFGHHþHHJHKJGEGIJHKHFGIIGKJJHJþ
IJJHGFJJHJGFJHJJJHJJþKKJJFGKKHFGHJKHIþHGFJJIKJIJIJþJGJJGJKIþKJKIÿþFþGFþGþFþJIGKIþFþFþGJKJKHIJþGþFGþHJIJJJEJIþFþFþGJJJJHJGHJJGþGHJIJFJKJFJJKJFþFþFJJGJJJGIJGKJIIGIþGJGJJJFHJHJJJJIFIHKJþJHJJJFHGJKE		JEIJGKJJIKIþHKJGJIHF		

GKIJJJIIþJHJJKGF			
F
IKHJHHþ
JJHIG				
H
GJHJJIþIHKJKFKJKFJIJJKKþJIJGJKIGJKJHþIKJGJJGJþIKJKÿþFþGþFþFþIFþGEþEþGJKGKIGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGþGJIJGJGEIJFJIKJFþ	FJEJ	JIGIJGKJIIGIþJHGJGJ	
EJIJEIJIJFIHKJþJHJJIGIKE	E
GHJIGJFEJGKJJIKIþHKKIKIH	G	HGJIKJHIKGKIIJJIIþJHJJKJKIFIIIKJIKJGJKHJHHþ
JJHJJJGJJIJHKKHJHJJIþIHKJIIJHKKJKJJKKþJIKIJKIJJKJHþIKJGJJGJþIKJKÿþGþFþIFþEþEþGJKGKþGþFþGJIKFIHIHþGþGHIIJIJIþFþFþJIJKKJGþFþGJIKIIGJGþFþFJEJJG	IGIGþJHGJGJFI		
FIHIJþJHJJIGIKJEF	
GKJKIKIþHKKIKIHG	G
IIJJIIþJHJJKIGF	GI
HJHHþ
JJHJJIH	G
JH
JIþIHK	F	HKF
I
JKKþJIJGJKIGJKJHþIIJGJIGJþIKJKÿþFþFþGFþGþFþJIGKIþFþFþGJEJIHIJþGþFGþHJIJGJJJJEJIþFþFþGIJJJJFIEJFJGHJJGþGHIIJFJJGKGJGEIJFJIKJFþFþFJIGJJJGJFIJIHKJIIGIþGJGJJJJIJJ	JIJFIHKJþJIJIJFH	JGJF	
FIJGKJJIKIþHKJGJF
FKHKHF	G
GKIIJJIIþJIJJKGIFJIHJ	GFHGIKHJHHþ
JJHIJGHJJIJHIGKJHJJIþIHKIIFJHKFJIJJKKþJIJGJKIGJKJHþIIJGJIGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIFJEJIþFþFþJIJKJGJGHKJGþFþGJIKIJEJ	IEIEJJIGJGþFþFJEJJGJJGIKJKKGKGHKKIIIIGþJHGJGJFIFKIJIIKJIEIJJJKJKHIJþJHJJIGIKGKGIHFGKJHFJIIJKIKIþHKKIKIIFI	GIJKIGIJKJIIþJHJJKJK	IKJGJIHJHHþ
JJHJJ	EKKHJHKJIþIHKJGE

GJKJJKKþJIJIGKJIJKJHþIKIGJJGJþJKJKÿþFþFþGFþGþFþJIGKIþFþFþGJEJIHIJþGþFGþHJIJIþFþFþGIJJ	HJJGþGHIIJ	
JFJIKJFþFþFJIGJJ		EJGKJIIGIþGJGJJJI			
FEIJJKFIHKJþJIJIJFH		

FGKGJFIJGKJJIKIþHKJGJF	
FFGIHIKGKIIJJIIþJIIJKGF
GKGJIIJGIKHJHHþ
JJHIJGHJIIJHJGHJHJJIþIHKIIFJHKFJIJJKKþJIJGJKIGJKJHþIIJGJIGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIJIþFþFþJIJKJGþFþGJIK	

JGþFþFJEJJ			

IIGþJHGJGJ			E

KHIJþJHJJIGIKE			
	
FFIJKIKIþHKKIKIGFF		E


GHJKJIIþJHIJIHFG	F
FGHJIHHHþ
JJKIGHGG	GHGHJIIJIþIHKJIIHHHJGHJJKKþJIGFJKIJJKJHþIKJGJJGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþFGþHIIKJGKFJEJIþFþFþGIJJKJGJIJGJGHKJGþFþ
GHIIJFJJKJJJIGJGþFþFþFJIGJJJGFJHKKIIIIGþGJGJJJFHJ	GKJJJKJKHIJþJIJIJFHGJKF	EIIJHFJIIJKIKIþHKJGJIHIHH	
F
GKJKIGIJKJIIþJIJJKJKIFG
HH
IKJGJIHJHHþ
JJHJJJGJGIJHJGHJHJJIþIHKJIIJHKFJIJJKKþJIKIJKIGJKJHþIKJGJIGJþIKJKÿþFþGþFþIFþEþEþGJKGKþGþFþFþGJIKEIHIIþGþGHIIKJGKFJEJIþFþFþJIJKJGJIJGJGHKJGþFþHJKFJIEIEJJIGJGþFþFJJGJKGIIIJIGþJHG		IEJIJKHIJþJHJJIE	G
KGHF		IJKIKIþHKKIGHF	
H
JIKGF

KJIIþJHIJKGIFJIHIKJIIF	G
JHHþ
KJHIJGHJJIJHKJHGHIJIþIHKIIFJHKFJKJIKJþJIJGJKIGJKJKþIIJGJIGJþIKJKÿþ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYYZWZ\[Y\þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[Y[WYYZZW[\[Y[\Z[\YY\Z[ZY\[þYZ\\[[[[Y\ZY[\[\[[X\[Z\Z\[\[[Y\[þ[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\þ[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\þ
YX\Z\[[ZWZ\[ZY[[[\Y\þ\\X[YY\\Z[W[W\[Yþ[\X[Z\[YZW[\þ\Y\[ZW[[þZ\Y\ÿþJJJJþJJKJKKIJþJJIJJKJJKKKJþJKJKJIKJKKKJJIJIþHJKKKLKKKLLLLKKJJJKJþ
JJIKJKLKLLKKLMLLKKKJKIJIþJHKJKLKKLLMMLLMNMLLLKKJJIHKJþJHJJJIKKLLNMMNNMNNNMMLLLKKKJJIKIþHKJJJKKKLKLMMMLMMLLLKKKJJJIHþIHJJKJKKJLLMLKLKKIJKIJIHþ
IJIJJJKKKLLKKJIKIJKIþIHKJIKKKLLKKKJKKþJIJIKKKKJKJIþIKJIJJIJþIKJKÿþ]YZ\þZ^_^\]^\þ\Z^___^^^^^_þ_____^_^]^^]^__^þ_^^__^^^^^]]]]^^_^^_þ
[\_^^^^^]]_]^\_^]^^__]]\þ\[^___^]]]]^][]]\]^]^^^^_]\[þYZ\^___^^^]\]^]_]]Z^]]]^^_\[[Y\[þ[Y^___^]]\[]]Z^^\[\\]^]\Y\[\þ[Y__^^]]\]\]]\]_][^^^^^\þ
YZ^^^]]\Y]^]\[\]]^]^þ\^^^][^^\\\\]]^]þ_^^]\\[YZY[\þ^^\[ZZ[[þZ\Y\ÿ