þDþDþDþDþEþDþcDcEdcEdEEedcEdcd[þEccEDFEccEFDdDdFEd\ZþEþEþdEFdDFEdFEdceEdEedF\Z[þFþFEecdcEdFedEDdcDcFdE[[[ZþEþdcdFcdcDFcdcEFEdcEddc\[[[[þdcdEcdcDdEDdcdDeFcdFcc[ZZ[\[þdDcEcDdcdEdFEdEcEcdDcde\[Z[[[[edcEdFdEdDeFceFDdDcdcEdd\[Z[[ZZ[þdFEdeccEcdDdeEcEDdDFe[[[[\[ZþcdcdcFDcEcdDcFEcEd[\[\\[þ
dcEcEdFEdEdDFdF\\\\\þFcFcdFDcDEde[[[[þdEdcEdEFd[[ZþceFEFd\[þdFd\ÿþDþDdEdDþDþDþEcDcEdEþEþdFdEdFDcdDþFdDdccceEdcEDþDþDþFcEcDdDdFcdFEdEþDþEdDdFdEeEDdEDdFeFcEþDþ
FeEcdDcDFEccEcdEdDFEdEþDþdDdcdeEdEdFdDFDcDcEdcEFcþEdcEddDdFDccdcEeEdEdFedcd[þDeEFcDEccEDdEcdcFDFDedcd\ZþdEdFddEFdDFEdcEdcdEdEdDc\Z[þDcDdcdDeFdcEdFedEDdcDcFdE[[[ZþEdEecdEcdcDdcdcEdEdcEddc\[[[[þccEcdEcdcDdEDdcdDcFcdccc[ZZ[\[þcdDFEcDdcdEdFEeEcEcdDcde\[Z[[[[edcEdFdEdDeccdFDdDcdcEdd\[Z[[ZZ[þceEdeFcEcdDcdEcEDdDcd[[[[\[ZþcdcdcFDcEccDcdEcEd[\[\\[þ
dcdcEdFEdEdDcdc\\\\\þccFcdcDcDEde[[[[þdEdcEdEFd[[ZþcdcEFd\[þdcd\ÿþEcþDþEcEdþEþdFdFedþFþFdDdccdFfGþDþdcEcDdcGefþFþEdDdFdEdEHfFfGþFeEcdDFEcfgGgeþDþdDdFdeEdFdefHfFfþEdcEddDdFDcdfFfeGefþFþFeEccDEccEdceGFeHGgFGþ
dEdFddEFdDFEdfHGffHfGHþDdDdccDeFdcEdceefHgFeeHFfþEeEecdEcdcDFcdcGefeGfegGgGFþccEcdDcdcDdEDdDdefFefeFfeGeeþcdDdEcEcDdEdFEcEcEfGfFeGeGfFfeþedcEdcdFDEeccdFDFcFeHgGfHfefGefgþcFcdecEFcdDcdEcEGdfeeGfgfGHfþedcdFdDcEDcDEcedeFfHfefHþ
dcdcEdFEdEcEdefGefefþEcFcdcDcDcFfeHeGþdEdcEdcdGfGfþceFEdefeþdFdfÿþDþDþDþDþDþdDcEdcEdFEcdcEdc\[þEccEDcEcFEcDeDdF\[[ZþEþEþdEFdDFEdcEdFdEdE[Z[[Z[þFþFEeFdcEdFedFDdcD[\\[[[[ZþEþFcdFddcDFcdcEdEd\\\\\\\[[[þccdDcdcDdEDdcdDc\\[YZ[ZZZ[\[þdDdEcEcDdEdFEeEc\\[YZZZ[[Z[[[[edcEdcdFDEeFcdFD\\[Z[ZZ[[[Z[[ZZ[þZ[\ZYZY[ZYZYZZ[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYYZWZ\[Y\þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[Y[WYYZZW[\[Y[\Z[\YY\Z[ZY\[þYZ\\[[[[Y\ZY[\[\[[X\[Z\Z\[\[[Y\[Z[[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\\[XXZ[[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\[\[ZWXXZZZYX\Z\[[ZWZ\[ZY[[[\Y\[\[[Z[XXZZ[[ZZ\\X[YY\\Z[W[W\[Y[\\[[[[Z[Z[\ZZ[\ZZ[\X[Z\[YZW[\\\\\\\\[[[[[\ZXXZ[ZXXZ\Y\[ZW[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZZ\Y\\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXZ\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþEþFEþEþeHFeHþEþEþFeEfHcHeþFþEFþdfHeFefeeEeHþEþEþFHfeefEHEeEeFcfeFþFdHffEdeFgFeFEHeEfHfeEþEþfHFfEeFeEHfHfHFHeFefHfFHþFeFefgeFeHfFfefEdHeEHdeFEHdfeþeHeHfecFefEdHFeeFefHFeEefFfeeEfHZ[cfeFfHcEFefdfEHfedHfFfHfefEH\[XXZ[eHeffFHEeHdFHeHEeFHfdede[\[ZWXXZZZeedHeFcfeHeefFcedeeH[\[[Z[XXZZ[[ZZHdfHeEfdfEeHfeff[\\[[[[Z[Z[\ZZ[\ZZfefFefHFefed\\\\\\\[[[[[\ZXXZ[ZXXZeHeFeHFe\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZHfef\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXZ\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþFþFþFfGfFþGfGeFeGþFþFfeFHfGfHfþGþFþFGefGfefgfefHþFþGfGefgHGfeFeGefþFþ
FþGeefefFGfFGfGfefFfGþ
GeGeFfGfFGeeGHFeFfgGgeþ	GeGefGeFfGHFfHfGfGgfefFfþFþZfefgHfGeHfGefeeFefFfeGefGþXZfeffFeFeeeeGfFGeeGFefGgHþWXYegfGfGfefGefGHFfHGfeGfGfþXXZZGfeeHefFHfgHfGefHgFeGfefFþ[Z[\ZeffFfgHfGefefFefeGfegGgGþ[[\ZXZeeGfeeeFfefFGfFefeffeGHeþX[\XXXZggeFfeGeGfGefGfFeFeGfFfeþZX[ZZXWZffGefeFfGefeegGeGfefGefgþX[\ZXWYeeFfFGeefGFfeeGHgfGfeþX[ZXXYfGeGefFeFGeFfHfefeþ
[[XXZefeFeGfGHfGefefþ[ZXZgfGfeFHfeeeGþ[XYfeGfGefGfþ[ZfeGHgeþZfHfÿþDþdeHgþEcEdGfgHþHþEþEþdEFdFdfGgfHIþFþFEeFdcdegHhgIhHfþGþ
EþdcdFddcDdcfIfGfgIgfHþGþFcdDcdeDdEcdHfgHGfgfGgfHþdDdEcDdDdEdFEeIHfIghGfHfHgGgþedcEeFdEDEeFcdFfgIghfgHGIgIhHfgfþY[\ZXWY[ZYYYZZ\\\\[[[[[[[\[\þX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþGþGþGþGþZ[gfHfgfHIgHfgHfGfþGþXXZ[hgGgIgHIgHIGHgfHþWXXZZZHhHfIgfIgHIGgfHfþHþHþXXZZ[[ZZGfgGHgfIgHhgfgHIþIþ[Z[\ZZ[\ZZhHgHfgfIGfghIgfgþHþ[[\ZXXZ[ZXXZfGgfgGHgGfgfGgffþX[\XXXX[ZXWWXZfHfHIfHgGfHfHgGgþZX[ZZXWX[ZXXWXZ\GIgfIfHGIgfhHfgfþX[\ZXWX[ZXXXXX\[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþGþGþGþHþZfegHghgHfgHGgIfGfþGþXYfdefFfIhfgHgfgHgfHþWXYefFGegfFeIhgfIHgIgGþHþHþXXZZdGHdFeGefefggIhghHfIþIþ[Z[\ZeefGfFfedFfefgfgIhgfgþHþ[[\ZXZfFHgfedFGefFfdfegfgfgIþX[\XXXZGfeFfeGedfGefdfFfdgFgfgþZX[ZZXWZefGFefFeFHfeegGeFfGfgHgfþX[\ZXWYfeGfFGfGfdFfeHdGgHdfeþX[ZXXYffeGedFeFGeFfeHefeþ
[[XXZefeFeffGHfGefefþ[ZXZefGFeFHfeHedþ[XYfHGfGefdfþ[ZfedHfeþZfefÿþDþDdEdDþDþEcDcEdEþEþdFdEdcDcdDþFdcdcccdEdcEDþDþDþdcEcDdDEEcdFEdEþDþEdDdcdEdEDFEDdFcFcEþDþ
FeEcdDFDcEeFEddEeDFEcEþDþdDdcdeEdEdFdDFDcDcEdFeFcþEdeEddDdcDccdcEdEdEdFedc\[þdeEccDEceEDdEcFcFDFDed\[[ZþdEddEdEcdDFEeFededEdE[Z[[Z[þDdeFccFecdcEdFddEDdcD[\\[[[[ZþEeEdDdcddeDdcdcEFEd\\\\\\\[[[þdcdceEcecDdEDdcdDc\\[YZ[ZZZ[\[þcdDcEcdcDdEdFEeEc\\[YZZZ[[Z[[[[decEdcdedEedcdFD\\[Z[ZZ[[[Z[[ZZ[þZ[\ZYZY[ZYZYZZ[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþFþFþFfGfFþGfGefeGþFþFfeFefGfHfþGþFþFGefGfeHefGfHþFþGeGgfeHfFfFeHefþFþ
FþGfHfefFGfFGfGfefFfGþ
GeGHFfFfeGfgGHFeFfFGgeþ	eHfefGfFfFHGeHfGfGgfHfFfþFþZ[gfgHgfgGfHfgefGffGffGefGþXXZ[hgGgGgefgFfGHgfHFeHGgFþWXXZZZHhehfghGgHfGgfHgfHfefþXXZZ[[ZZGfgGeHhfghfgfhefefFfFþ[Z[\ZZ[\ZZhHgefgfgGfggfgfgGeGþ[[\ZXXZ[ZXXZfGgfgGHgGfgfFgHfHeþX[\XXXX[ZXWWXZfehHfhHgGfGfegGgeþZX[ZZXWX[ZXXWXZ[GfgfgheGHgfhefghþX[\ZXWX[ZXXXXX\[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþFþFþFfGcdDþGfGeFceEdEþFfHFHfGEdFDFdDþFþFGefGfeHcEdEdcEDþDþ
FþGfGHfeHeFfdcEFcdFEdEþDþFþGeHeHgFGfFGfdEDdEDdFedcEþDþGefHFfFgfGHeGHFeFEcFEceEdDFEcEþeHGefGeGeFHffHgGdeFdDFDdDeEdFEccZfHfgefHfGfFeffeeddcEeEeddFedcd[XZfefgFgefeGeGeFdeEcFdedcDedcd\ZWXYfFfGfFfefFefGcdcEdcdEdEded\Z[XXZZGfHeGefFGfgHcedFDdcDcFdF[[[Z[Z[\ZeffHgfGfGfedcEeEddEddc\[[[[[[\ZXZeeffeHeFefedDdFcdFcc[ZZ[\[X[\XXXZgHeFfeGeGfdEcdDcde\[Z[[[[ZX[ZZXWZfeGefeFfdDcdcEdd\[Z[[ZZ[þX[\ZXWYfeFfFGFcEDdDFd[[[[\[ZþX[ZXXYfGeGHGdFEcEd[\[\\[þ
[[XXZefHFecdFdF\\\\\þ[ZXZgfGFdEde[[[[þ[XYfHGEcd[[Zþ[ZfHcd\[þZfd\ÿþHþGþGþGþEþDþEþZ[gfIfgfIHgHfgHfcEdFEdFEcdcEdc\[XXZ[hgGgfIHfgHIGdFEcFEcFdDde[\[ZWXXZZZHhHhIghIgHEdFDdcdEdE[\[[Z[XXZZ[[ZZGIgGHghIFEeEDdcD[\\[[[[Z[Z[\ZZ[\ZZhHgHfgdeEFEe\\\\\\\[[[[[\ZXXZ[ZXXZfGgfcdDd\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZIHEF\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXZ\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþDþDþDþDþEþDþcDcEdcEdEEedcEdcd[þEccEDFEccEFDdDdFEd[[þEþEþdEFdDFEdFEdceEdEedF\ZZþFþFEecdcEdFedEDdcDcFdE\Z[ZþEþdcdFcdcDFcdcEFEdcEddc[[[Z[þdcdEcdcDdEDdcdDeFcdFcc[ZYZ[[þdDcEcDdcdEdFEdEcEcdDcde\[[ZZ[ZedcEdFdEdDeFceFDdDcdcEdd[[\\[[[\Z[dFEdeccEcdDdeEcEDdDFe[Z[[[[[\[XXZ[cdcdcFDcEcdDcFEcEd\[[\[YZ[[ZWXXZZZdcEcEdFEdEdDFdF\\\\[[Z[[Z[XXZZ[[ZZFcFcdFDcDEde[[[\[\\[[[[Z[Z[\ZZ[\ZZdEdcEdEFd[[\\\\\\\\[[[[[\ZXXZ[ZXXZceFEFd[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZdFd[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXZ\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþDþDdEdDþDþDþEcDcEdEþEþdFdEdFDcdDþFdDdccceEdcEDþDþDþFcEcDdDdFcdFEdEþDþEdDdFdEeEDdEDdFeFcEþDþ
FeEcdDcDFEccEcdEdDFEdEþDþdDdcdeEdEdFdDFDcDcEdcEFcþEdcEddDdFDccdcEeEdEdFedcd[þDeEFcDEccEDdEcdcFDFDedcd[[þdEdFddEFdDFEdcEdcdEdEdDc\ZZþDcDdcdDeFdcEdFedEDdcDcFdE\Z[ZþEdEecdEcdcDdcdcEdEdcEddc[[[Z[þccEcdEcdcDdEDdcdDcFcdccc[ZYZ[[þcdDFEcDdcdEdFEeEcEcdDcde\[[ZZ[ZedcEdFdEdDeccdFDdDcdcEdd[[\\[[[\Z[ceEdeFcEcdDcdEcEDdDcd[Z[[[[[\[XXZ[cdcdcFDcEccDcdEcEd\[[\[YZ[[ZWXXZZZdcdcEdFEdEdDcdc\\\\[[Z[[Z[XXZZ[[ZZccFcdcDcDEde[[[\[\\[[[[Z[Z[\ZZ[\ZZdEdcEdEFd[[\\\\\\\\[[[[[\ZXXZ[ZXXZcdcEFd[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZdcd[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXZ\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ	þEcþDþEcEdþEþdFdFedþFþFdDdccdFfGþDþdcEcDdcGefþFþEdDdFdEdEHfFfGþFeEcdDFEcfgGgeþDþdDdFdeEdFdefHfFfþEdcEddDdFDcdfFfeGefþFþFeEccDEccEdceGFeHGgFGþ
dEdFddEFdDFEdfHGffHfGHþDdDdccDeFdcEdceefHgFeeHFfþEeEecdEcdcDFcdcGefeGfegGgGFþccEcdDcdcDdEDdDdefFefeFfeGeeþcdDdEcEcDdEdFEcEcEfGfFeGeGfFfeþedcEdcdFDEeccdFDFcFeHgGfHfefGefgZ[cFcdecEFcdDcdEcEGdfeeGfgfGHf\[XXZ[edcdFdDcEDcDEcedeFfHfefH[\[ZWXXZZZdcdcEdFEdEcEdefGefef[\[[Z[XXZZ[[ZZEcFcdcDcDcFfeHeG[\\[[[[Z[Z[\ZZ[\ZZdEdcEdcdGfGf\\\\\\\[[[[[\ZXXZ[ZXXZceFEdefe\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZdFdf\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXZ\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþDþDþDþDþDþdDcEdcEdFEcdcEdc\[þEccEDcEcFEcDeDdF\[[[þEþEþdEFdDFEdcEdFdEdE\[ZYZZþFþFEeFdcEdFedFDdcD\[\[ZZ[ZþEþFcdFddcDFcdcDdEd[\Z[[Z[[Z[þccdDcdcDdEDdcdEc[\\[[[[ZYZ[[þdDdEcEcDdEdFEeEc\[Z[[\\\[[ZZ[ZedcEdcdFDEeFcdFD[[[Z[YZ[[[\\[[[\Z[[YZZYZYZZ[ZZYZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ	þ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYYZWZ\[Y\þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[Y[WYYZZW[\[Y[\Z[\YY\Z[ZY\[þYZ\\[[[[Y\ZY[\[\[[X\[Z\Z\[\[[Y\[[Z[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\\[Z[[Z[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\\[[[XWX[Z[YX\Z\[[ZWZ\[ZY[[[\Y\\[ZYZZ[XXW[Z[Z\\X[YY\\Z[W[W\[Y\[\[ZZ[ZZ[XWW[[X[Z[\X[Z\[YZW[\[\Z[[Z[[Z[XX[ZXWW[ZXZ[\Y\[ZW[[[\\[[[[ZYZ[[XX\ZXWWX[\XXZ[Z\Y\\[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþEþFEþEþeHFeHþEþEþFeEfHcHeþFþEFþdfHeFefeeEeHþEþEþFHfeefEHEeEeFcfeFþFdHffEdeFgFeFEHeEfHfeEþEþfHFfEeFeEHfHfHFHeFefHfFHþFeFefgeFeHfFfefEdHeEHdeFEHdfeþeHeHfecFefEdHFeeFefHFeEefFfeeEfH[ZcfeFfHcEFefdfEHfedHfFfHfefEH\[Z[[ZeHeffFHEeHdFHeHEeFHfdede\[[[XWX[Z[eedHeFcfeHeefFcedeeH\[ZYZZ[XXW[Z[ZHdfHeEfdfEeHfeff\[\[ZZ[ZZ[XWW[[X[ZfefFefHFefed[\Z[[Z[[Z[XX[ZXWW[ZXZ[eHeFeHFe[\\[[[[ZYZ[[XX\ZXWWX[\XXZ[Hfef\[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþFþFþFfGfFþGfGeFeGþFþFfeFHfGfHfþGþFþFGefGfefgfefHþFþGfGefgHGfeFeGefþFþ
FþGeefefFGfFGfGfefFfGþ
GeGeFfGfFGeeGHFeFfgGgeþ	GeGefGeFfGHFfHfGfGgfefFfþFþ[fefgHfGeHfGefeeFefFfeGefGþZ[feffFeFeeeeGfFGeeGFefGgHþXWZegfGfGfefGefGHFfHGfeGfGfþ[XXYGfeeHefFHfgHfGefHgFeGfefFþZ[XWZeffFfgHfGefefFefeGfegGgGþXX[ZXZeeGfeeeFfefFGfFefeffeGHeþXX\ZXWYggeFfeGeGfGefGfFeFeGfFfeþ[\ZXZXXYffGefeFfGefeegGeGfefGefgX[[XXZXXZeeFfFGeefGFfeeGHgfGfe\[XXZ[XXZXXZfGeGefFeFGeFfHfefe[\[ZWXXZZZXZZXZefeFeGfGHfGefef[\[[Z[XXZZ[[ZZ\[Z[gfGfeFHfeeeG[\\[[[[Z[Z[\ZZ[\ZZ[[ZfeGfGefGf\\\\\\\[[[[[\ZXXZ[ZXWWZ[feGHge\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[fHf\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþDþdeHgþEcEdGfgHþHþEþEþdEFdFdfGgfHIþFþFEeFdcdegHhgIhHfþGþ
EþdcdFddcDdcfIfGfgIgfHþGþFcdDcdeDdEcdHfgHGfgfGgfHþdDdEcDdDdEdFEeIHfIghGfHfHgGgþedcEeFdEDEeFcdFfgIghfgHGIgIhHfgfZ[[YZZYZYZZ[ZZYZ\\\[[[\\\[[[\\\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþGþGþGþGþ[ZgfHfgfHIgHfgHfGfþGþZ[[ZhgGgIgHIgHIGHgfHþXWX[Z[HhHfIgfIgHIGgfHfþHþHþ[XXW[Z[ZGfgGHgfIgHhgfgHIþIþZ[XWW[[X[ZhHgHfgfIGfghIgfgþHþXX[ZXWW[ZXZ[fGgfgGHgGfgfGgffþXX\ZXWWX[\XXZ[fHfHIfHgGfHfHgGgþ[\ZXZXXWXZ[XWZ[[GIgfIfHGIgfhHfgfX[[XXZXXXWX[ZZXZ\\\[[[\\\[[[\\\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþGþGþGþHþ[fegHghgHfgHGgIfGfþGþZ[fdefFfIhfgHgfgHgfHþXWZefFGegfFeIhgfIHgIgGþHþHþ[XXYdGHdFeGefefggIhghHfIþIþZ[XWZeefGfFfedFfefgfgIhgfgþHþXX[ZXZfFHgfedFGefFfdfegfgfgIþXX\ZXWYGfeFfeGedfGefdfFfdgFgfgþ[\ZXZXXYefGFefFeFHfeegGeFfGfgHgfX[[XXZXXZfeGfFGfGfdFfeHdGgHdfe\[XXZ[XXZXXZffeGedFeFGeFfeHefe[\[ZWXXZZZXZZXZefeFeffGHfGefef[\[[Z[XXZZ[[ZZ\[Z[efGFeFHfeHed[\\[[[[Z[Z[\ZZ[\ZZ[[ZfHGfGefdf\\\\\\\[[[[[\ZXXZ[ZXWWZ[fedHfe\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[fef\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþDþDdEdDþDþEcDcEdEþEþdFdEdcDcdDþFdcdcccdEdcEDþDþDþdcEcDdDEEcdFEdEþDþEdDdcdEdEDFEDdFcFcEþDþ
FeEcdDFDcEeFEddEeDFEcEþDþdDdcdeEdEdFdDFDcDcEdFeFcþEdeEddDdcDccdcEdEdEdFedc\[þdeEccDEceEDdEcFcFDFDed\[[[þdEddEdEcdDFEeFededEdE\[ZYZZþDdeFccFecdcEdFddEDdcD\[\[ZZ[ZþEeEdDdcddeDdcdcEFEd[\Z[[Z[[Z[þdcdceEcecDdEDdcdDc[\\[[[[ZYZ[[þcdDcEcdcDdEdFEeEc\[Z[[\\\[[ZZ[ZdecEdcdedEedcdFD[[[Z[YZ[[[\\[[[\Z[[YZZYZYZZ[ZZYZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþFþFþFfGfFþGfGefeGþFþFfeFefGfHfþGþFþFGefGfeHefGfHþFþGeGgfeHfFfFeHefþFþ
FþGfHfefFGfFGfGfefFfGþ
GeGHFfFfeGfgGHFeFfFGgeþ	eHfefGfFfFHGeHfGfGgfHfFfþFþ[ZgfgHgfgGfHfgefGffGffGefGþZ[[ZhgGgGgefgFfGHgfHFeHGgFþXWX[Z[HhehfghGgHfGgfHgfHfefþ[XXW[Z[ZGfgGeHhfghfgfhefefFfFþZ[XWW[[X[ZhHgefgfgGfggfgfgGeGþXX[ZXWW[ZXZ[fGgfgGHgGfgfFgHfHeþXX\ZXWWX[\XXZ[fehHfhHgGfGfegGgeþ[\ZXZXXWXZ[XWZ[[GfgfgheGHgfhefghX[[XXZXXXWX[ZZXZ\\\[[[\\\[[[\\\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþFþFþFfGcdDþGfGeFceEdEþFfHFHfGEdFDFdDþFþFGefGfeHcEdEdcEDþDþ
FþGfGHfeHeFfdcEFcdFEdEþDþFþGeHeHgFGfFGfdEDdEDdFedcEþDþGefHFfFgfGHeGHFeFEcFEceEdDFEcEþeHGefGeGeFHffHgGdeFdDFDdDeEdFEcc[fHfgefHfGfFeffeeddcEeEeddFedcd[Z[fefgFgefeGeGeFdeEcFdedcDedcd[[XWZfFfGfFfefFefGcdcEdcdEdEded\ZZ[XXYGfHeGefFGfgHcedFDdcDcFdF\Z[ZZ[XWZeffHgfGfGfedcEeEddEddc[[[Z[XX[ZXZeeffeHeFefedDdFcdFcc[ZYZ[[XX\ZXWYgHeFfeGeGfdEcdDcde\[[ZZ[Z[\ZXZXXYfeGefeFfdDcdcEdd[[\\[[[\X[[XXZXXZfeFfFGFcEDdDFd[Z[[[[[\[XXZ[XXZXXZfGeGHGdFEcEd\[[\[YZ[[ZWXXZZZXZZXZefHFecdFdF\\\\[[Z[[Z[XXZZ[[ZZ\[Z[gfGFdEde[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZfHGEcd[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[fHcd[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[fd[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþHþGþGþGþEþDþEþ[ZgfIfgfIHgHfgHfcEdFEdFEcdcEdc\[Z[[ZhgGgfIHfgHIGdFEcFEcFdDde\[[[XWX[Z[HhHhIghIgHEdFDdcdEdE\[ZYZZ[XXW[Z[ZGIgGHghIFEeEDdcD\[\[ZZ[ZZ[XWW[[X[ZhHgHfgdeEFEe[\Z[[Z[[Z[XX[ZXWW[ZXZ[fGgfcdDd[\\[[[[ZYZ[[XX\ZXWWX[\XXZ[IHEF\[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþDþDþDþDþEþDþcDcEdcEdEEedcEdcd[þEccEDFEccEFDdDdFEd[ZþEþEþdEFdDFEdFEdceEdEedF[\[þFþFEecdcEdFedEDdcDcFdE[Z[\þEþdcdFcdcDFcdcEFEdcEddc[ZY[[þdcdEcdcDdEDdcdDeFcdFcc[[Z[[[þdDcEcDdcdEdFEdEcEcdDcde\\[[[[[edcEdFdEdDeFceFDdDcdcEdd[[[\\\[\[ZdFEdeccEcdDdeEcEDdDFe[[[[[[[\[Z[[ZcdcdcFDcEcdDcFEcEd\\[[\\[Z[[XWX[Z[dcEcEdFEdEdDFdF[YZ\\\[ZYZZ[XXW[Z[ZFcFcdFDcDEde\[ZZ[[\[ZZ[ZZ[XWW[[X[ZdEdcEdEFd\\[[[Z[[Z[[Z[XX[ZXWW[ZXZ[ceFEFdZ[[\\[[[[ZYZ[[XX\ZXWWX[\XXZ[dFdZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ þDþDdEdDþDþDþEcDcEdEþEþdFdEdFDcdDþFdDdccceEdcEDþDþDþFcEcDdDdFcdFEdEþDþEdDdFdEeEDdEDdFeFcEþDþ
FeEcdDcDFEccEcdEdDFEdEþDþdDdcdeEdEdFdDFDcDcEdcEFcþEdcEddDdFDccdcEeEdEdFedcd[þDeEFcDEccEDdEcdcFDFDedcd[ZþdEdFddEFdDFEdcEdcdEdEdDc[\[þDcDdcdDeFdcEdFedEDdcDcFdE[Z[\þEdEecdEcdcDdcdcEdEdcEddc[ZY[[þccEcdEcdcDdEDdcdDcFcdccc[[Z[[[þcdDFEcDdcdEdFEeEcEcdDcde\\[[[[[edcEdFdEdDeccdFDdDcdcEdd[[[\\\[\[ZceEdeFcEcdDcdEcEDdDcd[[[[[[[\[Z[[ZcdcdcFDcEccDcdEcEd\\[[\\[Z[[XWX[Z[dcdcEdFEdEdDcdc[YZ\\\[ZYZZ[XXW[Z[ZccFcdcDcDEde\[ZZ[[\[ZZ[ZZ[XWW[[X[ZdEdcEdEFd\\[[[Z[[Z[[Z[XX[ZXWW[ZXZ[cdcEFdZ[[\\[[[[ZYZ[[XX\ZXWWX[\XXZ[dcdZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþEcþDþEcEdþEþdFdFedþFþFdDdccdFfGþDþdcEcDdcGefþFþEdDdFdEdEHfFfGþFeEcdDFEcfgGgeþDþdDdFdeEdFdefHfFfþEdcEddDdFDcdfFfeGefþFþFeEccDEccEdceGFeHGgFGþ
dEdFddEFdDFEdfHGffHfGHþDdDdccDeFdcEdceefHgFeeHFfþEeEecdEcdcDFcdcGefeGfegGgGFþccEcdDcdcDdEDdDdefFefeFfeGeeþcdDdEcEcDdEdFEcEcEfGfFeGeGfFfeþedcEdcdFDEeccdFDFcFeHgGfHfefGefg[ZcFcdecEFcdDcdEcEGdfeeGfgfGHf\[Z[[ZedcdFdDcEDcDEcedeFfHfefH\[[[XWX[Z[dcdcEdFEdEcEdefGefef\[ZYZZ[XXW[Z[ZEcFcdcDcDcFfeHeG\[\[ZZ[ZZ[XWW[[X[ZdEdcEdcdGfGf[\Z[[Z[[Z[XX[ZXWW[ZXZ[ceFEdefe[\\[[[[ZYZ[[XX\ZXWWX[\XXZ[dFdf\[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþDþDþDþDþDþdDcEdcEdFEcdcEdc\[þEccEDcEcFEcDeDdF[[[ZþEþEþdEFdDFEdcEdFdEdE\\[[\[þFþFEeFdcEdFedFDdcD[\[[ZZ[\þEþFcdFddcDFcdcEdEd\[[ZZ[ZY[[þccdDcdcDdEDdcdDc\[[\[[[[Z[[[þdDdEcEcDdEdFEeEc\[Z[ZZ[\\[[[[[edcEdcdFDEeFcdFD[[ZZ[[[[Z[[\\\[\[ZZYZYY[[ZZZYZZYZZZ[\[[[[[[[[[\[Z[[ZZZXXZ[[ZXXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYYZWZ\[Y\þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[Y[WYYZZW[\[Y[\Z[\YY\Z[ZY\[þYZ\\[[[[Y\ZY[\[\[[X\[Z\Z\[\[[Y\[ZZ[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\\[ZXZZ[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\[[[ZZZXZZ[YX\Z\[[ZWZ\[ZY[[[\Y\\\[[\[Z[ZWXXZ[\\X[YY\\Z[W[W\[Y[\[[ZZ[\ZZZZXWXXZZ[\X[Z\[YZW[\\[[ZZ[ZY[[ZWX[ZZXWXXZZ\Y\[ZW[[\[[\[[[[Z[[[[XWX[[XZXZZXZZZ\Y\\[Z[ZZ[\\[[[[[Z[XZXZ[ZXXXZZXZZ[[ZZ[[[[Z[[\\\[\[ZZXXWW[[ZZZWWXXZZZ[\[[[[[[[[[\[Z[[ZZZXXZ[[ZXXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþeeeeþeefefcdeþcedeeeeeeeeeþeeeeeceeeceeceeeþcededeeefbeeefeeeefeþ
eedeeeeeecefededecfeddedþecdeeececfdeefceeeeeeebedcfeþeceeecdfefecebeeecefdeceedfeedfdZZcfededcdcefcfeefecefdfdeeedd\[ZXZZeceefeddedcfdeddebefcecc[[[ZZZXZZ[eeceeeceedeceececeed\\[[\[Z[ZWXXZ[dcfeddecffefeeff[\[[ZZ[\ZZZZXWXXZZededefdeefec\[[ZZ[ZY[[ZWX[ZZXWXXZZdfeceece\[[\[[[[Z[[[[XWX[[XZXZZXZZdfef\[Z[ZZ[\\[[[[[Z[XZXZ[ZXXXZZXZZ[[ZZ[[[[Z[[\\\[\[ZZXXWW[[ZZZWWXXZZZ[\[[[[[[[[[\[Z[[ZZZXXZ[[ZXXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ þFþFþFfGfFþGfGeFeGþFþFfeFHfGfHfþGþFþFGefGfefgfefHþFþGfGefgHGfeFeGefþFþ
FþGeefefFGfFGfGfefFfGþ
GeGeFfGfFGeeGHFeFfgGgeþ	GeGefGeFfGHFfHfGfGgfefFfþFþZfefgHfGeHfGefeeFefFfeGefGþZYfeffFeFeeeeGfFGeeGFefGgHþZZYegfGfGfefGefGHFfHGfeGfGfþZ[ZYGfeeHefFHfgHfGefHgFeGfefFþZZZZYeffFfgHfGefefFefeGfegGgGþZWX[ZZeeGfeeeFfefFGfFefeffeGHeþ[XWX[[YggeFfeGeGfGefGfFeFeGfFfeþZ[XZXZ[ZffGefeFfGefeegGeGfefGefg[ZZXXWW[[eeFfFGeefGFfeeGHgfGfe\[Z[[ZZZXXZ[fGeGefFeFGeFfHfefe\[[[XWX[Z[ZZXWZefeFeGfGHfGefef\[ZYZZ[XXW[Z[[ZXXZgfGfeFHfeeeG\[\[ZZ[ZZ[XWW[[X[[ZZYfeGfGefGf[\Z[[Z[[Z[XX[ZXWW[ZX[[ZZfeGHge[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZfHf\[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ	þDþdeHgþEcEdGfgHþHþEþEþdEFdFdfGgfHIþFþFEeFdcdegHhgIhHfþGþ
EþdcdFddcDdcfIfGfgIgfHþGþFcdDcdeDdEcdHfgHGfgfGgfHþdDdEcDdDdEdFEeIHfIghGfHfHgGgþedcEeFdEDEeFcdFfgIghfgHGIgIhHfgf[ZZYYYZ[[ZZZZYZY\\[[\[[[\\[[[\\\Z[[ZZZXXZ[[ZYXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþGþGþGþGþZZgfHfgfHIgHfgHfGfþGþZXZZhgGgIgHIgHIGHgfHþZZXZZ[HhHfIgfIgHIGgfHfþHþHþZ[ZWXXZ[GfgGHgfIgHhgfgHIþIþZZZZXWXXZYhHgHfgfIGfghIgfgþHþZWX[ZZXWXXYZfGgfgGHgGfgfGgffþ[XWX[[XZXZZXYZfHfHIfHgGfHfHgGgþZ[XZXZ[ZXXXZZXYZGIgfIfHGIgfhHfgf[ZZXXWW[[ZZZWWXX\\[[\\[[\\[[[\\\Z[[ZZZXXZ[[ZXXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþGþGþGþHþZfegHghgHfgHGgIfGfþGþZYfdefFfIhfgHgfgHgfHþZZYefFGegfFeIhgfIHgIgGþHþHþZ[ZYdGHdFeGefefggIhghHfIþIþZZZZYeefGfFfedFfefgfgIhgfgþHþZWX[ZZfFHgfedFGefFfdfegfgfgIþ[XWX[[YGfeFfeGedfGefdfFfdgFgfgþZ[XZXZ[ZefGFefFeFHfeegGeFfGfgHgf[ZZXXWW[[feGfFGfGfdFfeHdGgHdfe\[Z[[ZZZXXZ[ffeGedFeFGeFfeHefe\[[[XWX[Z[ZZXWZefeFeffGHfGefef\[ZYZZ[XXW[Z[[ZXXZefGFeFHfeHed\[\[ZZ[ZZ[XWW[[X[[ZZYfHGfGefdf[\Z[[Z[[Z[XX[ZXWW[ZX[[ZZfedHfe[\\[[[[ZYZ[[XX\ZXWWX[\XX[[Zfef\[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ þDþDdEdDþDþEcDcEdEþEþdFdEdcDcdDþFdcdcccdEdcEDþDþDþdcEcDdDEEcdFEdEþDþEdDdcdEdEDFEDdFcFcEþDþ
FeEcdDFDcEeFEddEeDFEcEþDþdDdcdeEdEdFdDFDcDcEdFeFcþEdeEddDdcDccdcEdEdEdFedc\[þdeEccDEceEDdEcFcFDFDed[[[ZþdEddEdEcdDFEeFededEdE\\[[\[þDdeFccFecdcEdFddEDdcD[\[[ZZ[\þEeEdDdcddeDdcdcEFEd\[[ZZ[ZY[[þdcdceEcecDdEDdcdDc\[[\[[[[Z[[[þcdDcEcdcDdEdFEeEc\[Z[ZZ[\\[[[[[decEdcdedEedcdFD[[ZZ[[[[Z[[\\\[\[ZZYYYZ[[ZZZZYZYZZZ[\[[[[[[[[[\[Z[[ZZZXXZ[[ZYXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ þFþFþFfGfFþGfGefeGþFþFfeFefGfHfþGþFþFGefGfeHefGfHþFþGeGgfeHfFfFeHefþFþ
FþGfHfefFGfFGfGfefFfGþ
GeGHFfFfeGfgGHFeFfFGgeþ	eHfefGfFfFHGeHfGfGgfHfFfþFþZZgfgHgfgGfHfgefGffGffGefGþZXZZhgGgGgefgFfGHgfHFeHGgFþZZXZZ[HhehfghGgHfGgfHgfHfefþZ[ZWXXZ[GfgGeHhfghfgfhefefFfFþZZZZXWXXZZhHgefgfgGfggfgfgGeGþZWX[ZZXWXXZZfGgfgGHgGfgfFgHfHeþ[XWX[[XZXZZXZZfehHfhHgGfGfegGgeþZ[XZXZ[ZXXXZZXZZGfgfgheGHgfhefgh[ZZXXWW[[ZZZWWXX\\[[\[[[\\[[[\\\Z[[ZZZXXZ[[ZXXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ þFþFþFfGcdDþGfGeFceEdEþFfHFHfGEdFDFdDþFþFGefGfeHcEdEdcEDþDþ
FþGfGHfeHeFfdcEFcdFEdEþDþFþGeHeHgFGfFGfdEDdEDdFedcEþDþGefHFfFgfGHeGHFeFEcFEceEdDFEcEþeHGefGeGeFHffHgGdeFdDFDdDeEdFEccZfHfgefHfGfFeffeeddcEeEeddFedcd[ZYfefgFgefeGeGeFdeEcFdedcDedcd[ZZZYfFfGfFfefFefGcdcEdcdEdEded[\[Z[ZYGfHeGefFGfgHcedFDdcDcFdF[Z[\ZZZZYeffHgfGfGfedcEeEddEddc[ZY[[ZWX[ZZeeffeHeFefedDdFcdFcc[[Z[[[[XWX[[YgHeFfeGeGfdEcdDcde\\[[[[[Z[XZXZ[ZfeGefeFfdDcdcEdd[[[\\\[\[ZZXXWW[[feFfFGFcEDdDFd[[[[[[[\[Z[[ZZZXXZ[fGeGHGdFEcEd\\[[\\[Z[[XWX[Z[ZZXWZefHFecdFdF[YZ\\\[ZYZZ[XXW[Z[[ZXXZgfGFdEde\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZYfHGEcd\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZfHcdZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZfdZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿþHþGþGþGþEþDþEþZZgfIfgfIHgHfgHfcEdFEdFEcdcEdc\[ZXZZhgGgfIHfgHIGdFEcFEcFdDde[[[ZZZXZZ[HhHhIghIgHEdFDdcdEdE\\[[\[Z[ZWXXZ[GIgGHghIFEeEDdcD[\[[ZZ[\ZZZZXWXXZZhHgHfgdeEFEe\[[ZZ[ZY[[ZWX[ZZXWXXZZfGgfcdDd\[[\[[[[Z[[[[XWX[[XZXZZXZZIHEF\[Z[ZZ[\\[[[[[Z[XZXZ[ZXXXZZXZZ[[ZZ[[[[Z[[\\\[\[ZZXXWW[[ZZZWWXXZZZ[\[[[[[[[[[\[Z[[ZZZXXZ[[ZXXWZ[YZ[[[\\[[\\[Z[[XWX[Z[ZZXWZ[XXXX[[[Z[ZYZ\\\[ZYZZ[XXW[Z[[ZXXZ[ZXX\\[[\[ZZ[[\[ZZ[ZZ[XWW[[X[[ZZX[[Z[[\\\[[[Z[[Z[[Z[XX[ZXWW[ZX[[ZZZ[YYZ[[\\[[[[ZYZ[[XX\ZXWWX[\XX[[ZZZZZ[Z[[\\\[[ZZ[Z[\ZXZXXWXZ[XWZ[[[[[Z[YZ[[[\\[[[\X[[XXZXXXWX[ZZXZ\\\[[[[[Z[[[[[\[XXZ[XXZXXXXZ[[XXZZ[\\\[[[\[YZ[[ZWXXZZZXZZXZZZZ[XZYZ[[\\\\[[Z[[Z[XXZZ[[ZZ\[Z[XWX[ZZ[Z[[[\[\\[[[[Z[Z[\ZZ[\ZZ[[ZXWX[[[[[\\\\\\\\[[[[[\ZXXZ[ZXWWZ[XXZZ[[\\[YZ[ZZZ[\[X[\XXXX[ZXWWXZ[Z[[\\[YZZZ[[Z[[[[ZX[ZZXWX[ZXXWXX\\\[Z[ZZ[[[Z[[ZZ[þX[\ZXWX[ZXXXXX[[\\[[[[[[[\[ZþX[ZXXXZ[XXXWZ[[[\\[\[\\[þ
[[XXXX[ZXXZ[Z[\\\\\\þ[ZXXW[[X[[[[[[[[þ[XXZZ[[[[[[Zþ[ZZZ[\\[þZX\\ÿ