þDþDþDþDþEþDþcDcEdcEdEEedcEdcd]þEccEDFEccEFDdDdFEd][þEþEþdEFdDFEdFEdceEdEedF][]þFþFEecdcEdFedEDdcDcFdE]\]^þEþdcdFcdcDFcdcEFEdcEddc][^\]þdcdEcdcDdEDdcdDeFcdFcc]]^\[]þdDcEcDdcdEdFEdEcEcdDcde]\[]\^\edcEdFdEdDeFceFDdDcdcEdd]\]\^]\^þdFEdeccEcdDdeEcEDdDFe]\[^[\^þcdcdcFDcEcdDcFEcEd]\Z^\]þ
dcEcEdFEdEdDFdF]\[][þFcFcdFDcDEde\^\^þdEdcEdEFd]][þceFEFd\[þdFd]ÿþDþDdEdDþDþDþEcDcEdEþEþdFdEdFDcdDþFdDdccceEdcEDþDþDþFcEcDdDdFcdFEdEþDþEdDdFdEeEDdEDdFeFcEþDþ
FeEcdDcDFEccEcdEdDFEdEþDþdDdcdeEdEdFdDFDcDcEdcEFcþEdcEddDdFDccdcEeEdEdFedcd]þDeEFcDEccEDdEcdcFDFDedcd][þdEdFddEFdDFEdcEdcdEdEdDc][]þDcDdcdDeFdcEdFedEDdcDcFdE]\]^þEdEecdEcdcDdcdcEdEdcEddc][^\]þccEcdEcdcDdEDdcdDcFcdccc]]^\[]þcdDFEcDdcdEdFEeEcEcdDcde]\[]\^\edcEdFdEdDeccdFDdDcdcEdd]\]\^]\^þceEdeFcEcdDcdEcEDdDcd]\[^[\^þcdcdcFDcEccDcdEcEd]\Z^\]þ
dcdcEdFEdEdDcdc]\[][þccFcdcDcDEde\^\^þdEdcEdEFd]][þcdcEFd\[þdcd]ÿþEcþDþEcEdþEþdFdFedþFþFdDdccdFfGþDþdcEcDdcGefþFþEdDdFdEdEHfFfGþFeEcdDFEcfgGgeþDþdDdFdeEdFdefHfFfþEdcEddDdFDcdfFfeGefþFþFeEccDEccEdceGFeHGgFGþ
dEdFddEFdDFEdfHGffHfGHþDdDdccDeFdcEdceefHgFeeHFfþEeEecdEcdcDFcdcGefeGfegGgGFþccEcdDcdcDdEDdDdefFefeFfeGeeþcdDdEcEcDdEdFEcEcEfGfFeGeGfFfeþedcEdcdFDEeccdFDFcFeHgGfHfefGefgþcFcdecEFcdDcdEcEGdfeeGfgfGHfþedcdFdDcEDcDEcedeFfHfefHþ
dcdcEdFEdEcEdefGefefþEcFcdcDcDcFfeHeGþdEdcEdcdGfGfþceFEdefeþdFdfÿþDþDþDþDþDþdDcEdcEdFEcdcEdc]\þEccEDcEcFEcDeDdF^]\[þEþEþdEFdDFEdcEdFdEdE\]]\[]þFþFEeFdcEdFedFDdcD^\^\]\]^þEþFcdFddcDFcdcEdEd\][\]\[^\]þccdDcdcDdEDdcdDc\\^]\]\]^\[]þdDdEcEcDdEdFEeEc^\[^[\]^\[]\^\edcEdcdFDEeFcdFD[\]^\]\]Z\]\^]\^þ[Z[ZZYZYZ[ZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYXZWZ\[Y[þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[YZWYYZZW[\[ZW\Z[\YY\Z[ZY\[þYZ\\[[Z[Y\ZY[\Z\[[X\[Z\W\[\[[Y\[ZZ[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\]\Y[ZY[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\[]\[XZY[ZXYX\Z\[[ZWZ\[ZY[[[\Y\[]]\[]ZYZZYZZZ\\X[YY\\Z[X[W\[Y^\^\]\]^[Z[XY[Y[ZX[\X[Z\[YZY[\Z][\]\[^\]Y[ZZZYZZ[YZY\Y\[ZW[[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZZ\Y\^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþEþFEþEþeHFeHþEþEþFeEfHcHeþFþEFþdfHeFefeeEeHþEþEþFHfeefEHEeEeFcfeFþFdHffEdeFgFeFEHeEfHfeEþEþfHFfEeFeEHfHfHFHeFefHfFHþFeFefgeFeHfFfefEdHeEHdeFEHdfeþeHeHfecFefEdHFeeFefHFeEefFfeeEfH[ZcfeFfHcEFefdfEHfedHfFfHfefEH]\Y[ZYeHeffFHEeHdFHeHEeFHfdede^]\[XZY[Z[eedHeFcfeHeefFcedeeH\]]\[]ZYZZYZZ[HdfHeEfdfEeHfeff^\^\]\]^[Z[XY[Y[Z[fefFefHFefed\][\]\[^\]Y[ZZZYZZ[YZYeHeFeHFe\\^]\]\]^\[]ZZY[Y[ZYZ[YZ[ZHfef^\[^[\]^\[]\^\ZXZZYZYXWZZYZY[Z[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþFþFþFfGfFþGfGeFeGþFþFfeFHfGfHfþGþFþFGefGfefgfefHþFþGfGefgHGfeFeGefþFþ
FþGeefefFGfFGfGfefFfGþ
GeGeFfGfFGeeGHFeFfgGgeþ	GeGefGeFfGHFfHfGfGgfefFfþFþZfefgHfGeHfGefeeFefFfeGefGþY[feffFeFeeeeGfFGeeGFefGgHþXZ[egfGfGfefGefGHFfHGfeGfGfþZYZZGfeeHefFHfgHfGefHgFeGfefFþ[Z[X[effFfgHfGefefFefeGfegGgGþY[ZZZ[eeGfeeeFfefFGfFefeffeGHeþZZY[Y[ZggeFfeGeGfGefGfFeFeGfFfeþZXZZYZY[ffGefeFfGefeegGeGfefGefgþYZXZZY[eeFfFGeefGFfeeGHgfGfeþZY[ZYZfGeGefFeFGeFfHfefeþ
Y[ZXYefeFeGfGHfGefefþ[Y[ZgfGfeFHfeeeGþZYZfeGfGefGfþ[ZfeGHgeþYfHfÿþDþdeHgþEcEdGfgHþHþEþEþdEFdFdfGgfHIþFþFEeFdcdegHhgIhHfþGþ
EþdcdFddcDdcfIfGfgIgfHþGþFcdDcdeDdEcdHfgHGfgfGgfHþdDdEcDdDdEdFEeIHfIghGfHfHgGgþedcEeFdEDEeFcdFfgIghfgHGIgIhHfgfþ[Z[ZZYZYZ[ZZ[Z]^]]\]^]\]^]\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþGþGþGþGþ[ZgfHfgfHIgHfgHfGfþGþY[ZYhgGgIgHIgHIGHgfHþXZY[Z[HhHfIgfIgHIGgfHfþHþHþZYZZYZZ[GfgGHgfIgHhgfgHIþIþ[Z[XY[Y[Z[hHgHfgfIGfghIgfgþHþY[ZZZYZZ[YZYfGgfgGHgGfgfGgffþZZY[Y[ZYZ[YZ[ZfHfHIfHgGfHfHgGgþZXZZYZYXWZZYZY[ZGIgfIfHGIgfhHfgfþYZXZZYZYZYZZ[Z]^]]\]^]\]^]\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþGþGþGþHþZfegHghgHfgHGgIfGfþGþY[fdefFfIhfgHgfgHgfHþXZ[efFGegfFeIhgfIHgIgGþHþHþZYZZdGHdFeGefefggIhghHfIþIþ[Z[X[eefGfFfedFfefgfgIhgfgþHþY[ZZZ[fFHgfedFGefFfdfegfgfgIþZZY[Y[ZGfeFfeGedfGefdfFfdgFgfgþZXZZYZY[efGFefFeFHfeegGeFfGfgHgfþYZXZZY[feGfFGfGfdFfeHdGgHdfeþZY[ZYZffeGedFeFGeFfeHefeþ
Y[ZWYefeFeffGHfGefefþ[Y[ZefGFeFHfeHedþZYZfHGfGefdfþ[ZfedHfeþYfefÿþDþDdEdDþDþEcDcEdEþEþdFdEdcDcdDþFdcdcccdEdcEDþDþDþdcEcDdDEEcdFEdEþDþEdDdcdEdEDFEDdFcFcEþDþ
FeEcdDFDcEeFEddEeDFEcEþDþdDdcdeEdEdFdDFDcDcEdFeFcþEdeEddDdcDccdcEdEdEdFedc]\þdeEccDEceEDdEcFcFDFDed^]\[þdEddEdEcdDFEeFededEdE\]]\[]þDdeFccFecdcEdFddEDdcD^\^\]\]^þEeEdDdcddeDdcdcEFEd\][\]\[^\]þdcdceEcecDdEDdcdDc\\^]\]\]^\[]þcdDcEcdcDdEdFEeEc^\[^[\]^\[]\^\decEdcdedEedcdFD[\]^\]\]Z\]\^]\^þ[Z[ZZYZYZ[ZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþFþFþFfGfFþGfGefeGþFþFfeFefGfHfþGþFþFGefGfeHefGfHþFþGeGgfeHfFfFeHefþFþ
FþGfHfefFGfFGfGfefFfGþ
GeGHFfFfeGfgGHFeFfFGgeþ	eHfefGfFfFHGeHfGfGgfHfFfþFþ[ZgfgHgfgGfHfgefGffGffGefGþY[ZYhgGgGgefgFfGHgfHFeHGgFþXZY[Z[HhehfghGgHfGgfHgfHfefþZYZZYZZ[GfgGeHhfghfgfhefefFfFþ[Z[XY[Y[Z[hHgefgfgGfggfgfgGeGþY[ZZZYZZ[YZYfGgfgGHgGfgfFgHfHeþZZY[Y[ZYZ[YZ[ZfehHfhHgGfGfegGgeþZXZZYZYXWZZYZY[ZGfgfgheGHgfhefghþYZXZZYZYZYZZ[Z]^]]\]^]\]^]\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþFþFþFfGcdDþGfGeFceEdEþFfHFHfGEdFDFdDþFþFGefGfeHcEdEdcEDþDþ
FþGfGHfeHeFfdcEFcdFEdEþDþFþGeHeHgFGfFGfdEDdEDdFedcEþDþGefHFfFgfGHeGHFeFEcFEceEdDFEcEþeHGefGeGeFHffHgGdeFdDFDdDeEdFEccZfHfgefHfGfFeffeeddcEeEeddFedcd]Y[fefgFgefeGeGeFdeEcFdedcDedcd][XZ[fFfGfFfefFefGcdcEdcdEdEded][]ZYZZGfHeGefFGfgHcedFDdcDcFdF]\]^[Z[X[effHgfGfGfedcEeEddEddc][^\]Y[ZZZ[eeffeHeFefedDdFcdFcc]]^\[]ZZY[Y[ZgHeFfeGeGfdEcdDcde]\[]\^\ZXZZYZY[feGefeFfdDcdcEdd]\]\^]\^þYZXZZY[feFfFGFcEDdDFd]\[^[\^þZY[ZYZfGeGHGdFEcEd]\Z^\]þ
Y[ZWYefHFecdFdF]\[][þ[Y[ZgfGFdEde\^\^þZYZfHGEcd]][þ[ZfHcd\[þYfd]ÿþHþGþGþGþEþDþEþ[ZgfIfgfIHgHfgHfcEdFEdFEcdcEdc]\Y[ZYhgGgfIHfgHIGdFEcFEcFdDde^]\[XZY[Z[HhHhIghIgHEdFDdcdEdE\]]\[]ZYZZYZZ[GIgGHghIFEeEDdcD^\^\]\]^[Z[XY[Y[Z[hHgHfgdeEFEe\][\]\[^\]Y[ZZZYZZ[YZYfGgfcdDd\\^]\]\]^\[]ZZY[Y[ZYZ[YZ[ZIHEF^\[^[\]^\[]\^\ZXZZYZYXWZZYZY[Z[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþDþDþDþDþEþDþcDcEdcEdEEedcEdcd\þEccEDFEccEFDdDdFEd]]þEþEþdEFdDFEdFEdceEdEedF\[]þFþFEecdcEdFedEDdcDcFdE]\][þEþdcdFcdcDFcdcEFEdcEddc\[^\]þdcdEcdcDdEDdcdDeFcdFcc]]^\[ZþdDcEcDdcdEdFEdEcEcdDcde^\[]\^]edcEdFdEdDeFceFDdDcdcEdd]\]\^]\][ZdFEdeccEcdDdeEcEDdDFe]\[^[Z^]\Y[ZYcdcdcFDcEcdDcFEcEd]\]^\][]\[XZY[Z[dcEcEdFEdEdDFdF]\[][[]]\[]ZYZZYZZ[FcFcdFDcDEde\^\^^\^\]\]^[Z[XY[Y[Z[dEdcEdEFd]][Z][\]\[^\]Y[ZZZYZZ[YZYceFEFd][Z\^]\]\]^\[]ZZY[Y[ZYZ[YZ[ZdFd]^\[^[\]^\[]\^\ZXZZYZYXWZZYZY[Z[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþDþDdEdDþDþDþEcDcEdEþEþdFdEdFDcdDþFdDdccceEdcEDþDþDþFcEcDdDdFcdFEdEþDþEdDdFdEeEDdEDdFeFcEþDþ
FeEcdDcDFEccEcdEdDFEdEþDþdDdcdeEdEdFdDFDcDcEdcEFcþEdcEddDdFDccdcEeEdEdFedcd\þDeEFcDEccEDdEcdcFDFDedcd\]þdEdFddEFdDFEdcEdcdEdEdDc\[]þDcDdcdDeFdcEdFedEDdcDcFdE]\][þEdEecdEcdcDdcdcEdEdcEddc\[^\]þccEcdEcdcDdEDdcdDcFcdccc]]^\[ZþcdDFEcDdcdEdFEeEcEcdDcde^\[]\^]edcEdFdEdDeccdFDdDcdcEdd]\]\^]\][ZceEdeFcEcdDcdEcEDdDcd]\[^[Z^]\Y[ZYcdcdcFDcEccDcdEcEd]\]^\][]\[XZY[Z[dcdcEdFEdEdDcdc]\[][[]]\[]ZYZZYZZ[ccFcdcDcDEde\^\^^\^\]\]^[Z[XY[Y[Z[dEdcEdEFd\][Z][\]\[^\]Y[ZZZYZZ[YZYcdcEFd][Z\^]\]\]^\[]ZZY[Y[ZYZ[YZ[Zdcd]^\[^[\]^\[]\^\ZXZZYZYXWZZYZY[Z[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ	þEcþDþEcEdþEþdFdFedþFþFdDdccdFfGþDþdcEcDdcGefþFþEdDdFdEdEHfFfGþFeEcdDFEcfgGgeþDþdDdFdeEdFdefHfFfþEdcEddDdFDcdfFfeGefþFþFeEccDEccEdceGFeHGgFGþ
dEdFddEFdDFEdfHGffHfGHþDdDdccDeFdcEdceefHgFeeHFfþEeEecdEcdcDFcdcGefeGfegGgGFþccEcdDcdcDdEDdDdefFefeFfeGeeþcdDdEcEcDdEdFEcEcEfGfFeGeGfFfeþedcEdcdFDEeccdFDFcFeHgGfHfefGefg[ZcFcdecEFcdDcdEcEGdfeeGfgfGHf]\Y[ZYedcdFdDcEDcDEcedeFfHfefH^]\[XZY[Z[dcdcEdFEdEcEdefGefef\]]\[]ZYZZYZZ[EcFcdcDcDcFfeHeG^\^\]\]^[Z[XY[Y[Z[dEdcEdcdGfGf\][\]\[^\]Y[ZZZYZZ[YZYceFEdefe\\^]\]\]^\[]ZZY[Y[ZYZ[YZ[ZdFdf^\[^[\]^\[]\^\ZXZZYZYXWZZYZY[Z[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþDþDþDþDþDþdDcEdcEdFEcdcEdc]\þEccEDcEcFEcDeDdF]]Z]þEþEþdEFdDFEdcEdFdEdE]^^\[]þFþFEeFdcEdFedFDdcD^\^\]\][þEþFcdFddcDFcdcDdEd]][\]\[^\]þccdDcdcDdEDdcdEc]\^]\]Z]^\[ZþdDdEcEcDdEdFEeEc^\[^[\]^\[]\^]edcEdcdFDEeFcdFD]\]^\]\]Z\]\^]\]ZZ[Z[ZZYZYZ[ZZ[[\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ	þ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYXZWZ\[Y[þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[YZWYYZZW[\[ZW\Z[\YY\Z[ZY\[þYZ\\[[Z[Y\ZY[\Z\[[X\[Z\W\[\[[Y\[ZZ[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\]\YWZY[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\[]Z]X[Y[ZWYX\Z\[[ZWZ\[ZY[[[\Y\Z]^\[]ZYYZYZZZ\\X[YY\\Z[X[W\[Y^\^\]\][YZ[YX[Y[ZX[\X[Z\[YZY[\Z][\]\[^\]Y[ZZZYZZ[YZX\Y\[ZW[[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[Z\Y\^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþEþFEþEþeHFeHþEþEþFeEfHcHeþFþEFþdfHeFefeeEeHþEþEþFHfeefEHEeEeFcfeFþFdHffEdeFgFeFEHeEfHfeEþEþfHFfEeFeEHfHfHFHeFefHfFHþFeFefgeFeHfFfefEdHeEHdeFEHdfeþeHeHfecFefEdHFeeFefHFeEefFfeeEfHZZcfeFfHcEFefdfEHfedHfFfHfefEH]\YWZ[eHeffFHEeHdFHeHEeFHfdede\]Z]X[Y[Z[eedHeFcfeHeefFcedeeH\]^\[]ZYYZYZZZHdfHeEfdfEeHfeff^\^\]\][YZ[YX[Y[Z[fefFefHFefed\][\]\[^\]Y[ZZZYZZ[YZ[eHeFeHFe]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[Hfef^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþFþFþFfGfFþGfGeFeGþFþFfeFHfGfHfþGþFþFGefGfefgfefHþFþGfGefgHGfeFeGefþFþ
FþGeefefFGfFGfGfefFfGþ
GeGeFfGfFGeeGHFeFfgGgeþ	GeGefGeFfGHFfHfGfGgfefFfþFþZfefgHfGeHfGefeeFefFfeGefGþYZfeffFeFeeeeGfFGeeGFefGgHþX[ZegfGfGfefGefGHFfHGfeGfGfþZYYZGfeeHefFHfgHfGefHgFeGfefFþYZ[Y[effFfgHfGefefFefeGfegGgGþY[ZZZYeeGfeeeFfefFGfFefeffeGHeþZZY[Y[ZggeFfeGeGfGefGfFeFeGfFfeþZ[ZXWZYZffGefeFfGefeegGeGfefGefgZZYZYZZYZeeFfFGeefGFfeeGHgfGfe]\Y[ZYZY[ZY[fGeGefFeFGeFfHfefe\]\[XZY[ZXY[ZZYefeFeGfGHfGefef\]_\[]ZYZZYZZZ[Y[ZgfGfeFHfeeeG^\^\]\]^[Z[XY[Y[ZXZYZfeGfGefGf\][\]\[^\]Y[ZZZYZZ[YZY[ZfeGHge\\^]\]\]^\[]ZZY[Y[ZYZ[YZWZ[fHf^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþDþdeHgþEcEdGfgHþHþEþEþdEFdFdfGgfHIþFþFEeFdcdegHhgIhHfþGþ
EþdcdFddcDdcfIfGfgIgfHþGþFcdDcdeDdEcdHfgHGfgfGgfHþdDdEcDdDdEdFEeIHfIghGfHfHgGgþedcEeFdEDEeFcdFfgIghfgHGIgIhHfgfZZ[Z[ZZYZYZ[ZZ[[\^\]]\^]\[^[\^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþGþGþGþGþZZgfHfgfHIgHfgHfGfþGþYWZ[hgGgIgHIgHIGHgfHþX[Y[Z[HhHfIgfIgHIGgfHfþHþHþZYYZYZZZGfgGHgfIgHhgfgHIþIþYZ[YX[Y[Z[hHgHfgfIGfghIgfgþHþY[ZZZYZZ[YZ[fGgfgGHgGfgfGgffþZZY[Y[ZYZ[YZZ[fHfHIfHgGfHfHgGgþZ[ZXWZYXWZZYZYZ[GIgfIfHGIgfhHfgfZZYZYZZYZYZXZZ[Z\^\]]\^]\[^[\^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþGþGþGþHþZfegHghgHfgHGgIfGfþGþYZfdefFfIhfgHgfgHgfHþX[ZefFGegfFeIhgfIHgIgGþHþHþZYYZdGHdFeGefefggIhghHfIþIþYZ[Y[eefGfFfedFfefgfgIhgfgþHþY[ZZZYfFHgfedFGefFfdfegfgfgIþZZY[Y[ZGfeFfeGedfGefdfFfdgFgfgþZ[ZXWZYZefGFefFeFHfeegGeFfGfgHgfZZYZYZZYZfeGfFGfGfdFfeHdGgHdfe]\Y[ZYZY[ZY[ffeGedFeFGeFfeHefe\]\[XZY[ZXY[ZZYefeFeffGHfGefef\]_\[]ZYZZYZZZ[Y[ZefGFeFHfeHed^\^\]\]^[Z[XY[Y[ZXZYZfHGfGefdf\][\]\[^\]Y[ZZZYZZ[YZY[ZfedHfe\\^]\]\]^\[]ZZY[Y[ZYZ[YZWZ[fef^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþDþDdEdDþDþEcDcEdEþEþdFdEdcDcdDþFdcdcccdEdcEDþDþDþdcEcDdDEEcdFEdEþDþEdDdcdEdEDFEDdFcFcEþDþ
FeEcdDFDcEeFEddEeDFEcEþDþdDdcdeEdEdFdDFDcDcEdFeFcþEdeEddDdcDccdcEdEdEdFedc]\þdeEccDEceEDdEcFcFDFDed]]Z]þdEddEdEcdDFEeFededEdE]^^\[]þDdeFccFecdcEdFddEDdcD^\^\]\][þEeEdDdcddeDdcdcEFEd]][\]\[^\]þdcdceEcecDdEDdcdDc]\^]\]Z]^\[ZþcdDcEcdcDdEdFEeEc^\[^[\]^\[]\^]decEdcdedEedcdFD]\]^\]\]Z\]\^]\]ZZ[Z[ZZYZYZ[ZZ[[\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþFþFþFfGfFþGfGefeGþFþFfeFefGfHfþGþFþFGefGfeHefGfHþFþGeGgfeHfFfFeHefþFþ
FþGfHfefFGfFGfGfefFfGþ
GeGHFfFfeGfgGHFeFfFGgeþ	eHfefGfFfFHGeHfGfGgfHfFfþFþZZgfgHgfgGfHfgefGffGffGefGþYWZ[hgGgGgefgFfGHgfHFeHGgFþX[Y[Z[HhehfghGgHfGgfHgfHfefþZYYZYZZZGfgGeHhfghfgfhefefFfFþYZ[YX[Y[Z[hHgefgfgGfggfgfgGeGþY[ZZZYZZ[YZ[fGgfgGHgGfgfFgHfHeþZZY[Y[ZYZ[YZZ[fehHfhHgGfGfegGgeþZ[ZXWZYXWZZYZYZ[GfgfgheGHgfhefghZZYZYZZYZYZXZZ[Z\^\]]\^]\[^[\^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþFþFþFfGcdDþGfGeFceEdEþFfHFHfGEdFDFdDþFþFGefGfeHcEdEdcEDþDþ
FþGfGHfeHeFfdcEFcdFEdEþDþFþGeHeHgFGfFGfdEDdEDdFedcEþDþGefHFfFgfGHeGHFeFEcFEceEdDFEcEþeHGefGeGeFHffHgGdeFdDFDdDeEdFEccZfHfgefHfGfFeffeeddcEeEeddFedcd\YZfefgFgefeGeGeFdeEcFdedcDedcd\]X[ZfFfGfFfefFefGcdcEdcdEdEded\[]ZYYZGfHeGefFGfgHcedFDdcDcFdF]\][YZ[Y[effHgfGfGfedcEeEddEddc\[^\]Y[ZZZYeeffeHeFefedDdFcdFcc]]^\[ZZZY[Y[ZgHeFfeGeGfdEcdDcde^\[]\^]Z[ZXWZYZfeGefeFfdDcdcEdd]\]\^]\]ZZYZYZZYZfeFfFGFcEDdDFd]\[^[Z^]\Y[ZYZY[ZY[fGeGHGdFEcEd]\]^\][]\[XZY[ZXY[ZZYefHFecdFdF]\[][[]]\[]ZYZZYZZZ[Y[ZgfGFdEde\^\^^\^\]\]^[Z[XY[Y[ZXZYZfHGEcd\][Z][\]\[^\]Y[ZZZYZZ[YZY[ZfHcd][Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZ[fd]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþHþGþGþGþEþDþEþZZgfIfgfIHgHfgHfcEdFEdFEcdcEdc]\YWZ[hgGgfIHfgHIGdFEcFEcFdDde\]Z]X[Y[Z[HhHhIghIgHEdFDdcdEdE\]^\[]ZYYZYZZZGIgGHghIFEeEDdcD^\^\]\][YZ[YX[Y[Z[hHgHfgdeEFEe\][\]\[^\]Y[ZZZYZZ[YZ[fGgfcdDd]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[IHEF^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþDþDþDþDþEþDþcDcEdcEdEEedcEdcd\þEccEDFEccEFDdDdFEd\]þEþEþdEFdDFEdFEdceEdEedF^[^þFþFEecdcEdFedEDdcDcFdE]\]\þEþdcdFcdcDFcdcEFEdcEddc\[^Z]þdcdEcdcDdEDdcdDeFcdFcc\]^\[]þdDcEcDdcdEdFEdEcEcdDcde^\[]\^\edcEdFdEdDeFceFDdDcdcEdd]\]\^]\^ZZdFEdeccEcdDdeEcEDdDFe]\[^[\^]\YWZ[cdcdcFDcEcdDcFEcEd]\]^\\[]Z]X[Y[Z[dcEcEdFEdEdDFdF]Z[][Z]^\[]ZYYZYZZZFcFcdFDcDEde\^\^^\^\]\][YZ[YX[Y[Z[dEdcEdEFd\][Z][\]\[^\]Y[ZZZYZZ[YZ[ceFEFd\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[dFd]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ þDþDdEdDþDþDþEcDcEdEþEþdFdEdFDcdDþFdDdccceEdcEDþDþDþFcEcDdDdFcdFEdEþDþEdDdFdEeEDdEDdFeFcEþDþ
FeEcdDcDFEccEcdEdDFEdEþDþdDdcdeEdEdFdDFDcDcEdcEFcþEdcEddDdFDccdcEeEdEdFedcd\þDeEFcDEccEDdEcdcFDFDedcd\]þdEdFddEFdDFEdcEdcdEdEdDc^[^þDcDdcdDeFdcEdFedEDdcDcFdE]\]\þEdEecdEcdcDdcdcEdEdcEddc\[^Z]þccEcdEcdcDdEDdcdDcFcdccc\]^\[]þcdDFEcDdcdEdFEeEcEcdDcde^\[]\^\edcEdFdEdDeccdFDdDcdcEdd]\]\^]\^ZZceEdeFcEcdDcdEcEDdDcd]\[^[\^]\YWZ[cdcdcFDcEccDcdEcEd]\]^\\[]Z]X[Y[Z[dcdcEdFEdEdDcdc]Z[][Z]^\[]ZYYZYZZZccFcdcDcDEde\^\^^\^\]\][YZ[YX[Y[Z[dEdcEdEFd\][Z][\]\[^\]Y[ZZZYZZ[YZ[cdcEFd\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[dcd]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþEcþDþEcEdþEþdFdFedþFþFdDdccdFfGþDþdcEcDdcGefþFþEdDdFdEdEHfFfGþFeEcdDFEcfgGgeþDþdDdFdeEdFdefHfFfþEdcEddDdFDcdfFfeGefþFþFeEccDEccEdceGFeHGgFGþ
dEdFddEFdDFEdfHGffHfGHþDdDdccDeFdcEdceefHgFeeHFfþEeEecdEcdcDFcdcGefeGfegGgGFþccEcdDcdcDdEDdDdefFefeFfeGeeþcdDdEcEcDdEdFEcEcEfGfFeGeGfFfeþedcEdcdFDEeccdFDFcFeHgGfHfefGefgZZcFcdecEFcdDcdEcEGdfeeGfgfGHf]\YWZ[edcdFdDcEDcDEcedeFfHfefH\]Z]X[Y[Z[dcdcEdFEdEcEdefGefef\]^\[]ZYYZYZZZEcFcdcDcDcFfeHeG^\^\]\][YZ[YX[Y[Z[dEdcEdcdGfGf\][\]\[^\]Y[ZZZYZZ[YZ[ceFEdefe]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[dFdf^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþDþDþDþDþDþdDcEdcEdFEcdcEdc]\þEccEDcEcFEcDeDdF[]\]þEþEþdEFdDFEdcEdFdEdE]]^\[^þFþFEeFdcEdFedFDdcD]]^\]\]\þEþFcdFddcDFcdcEdEd[][\]Z[^Z]þccdDcdcDdEDdcdDc]]^]\Z\]^\[]þdDdEcEcDdEdFEeEc\][^[\]^\[]\^\edcEdcdFDEeFcdFD\]]^Z]\]]\]\^]\^ZZ[ZYZZ[ZYZ[ZZ[Z]^\][\^]\[^[\^]\YWZYZY[ZYZ[Y[YZ[\[Z^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYXZWZ\[Y[þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[YZWYYZZW[\[ZW\Z[\YY\Z[ZY\[þYZ\\[[Z[Y\ZY[\Z\[[X\[Z\W\[\[[Y\[ZZ[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[]]\X[ZY[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\[]\][ZY[ZYYX\Z\[[ZWZ\[ZY[[[\Y\[]^\[^ZYXZYZZZ\\X[YY\\Z[X[W\[Y]\^\]\]\[Z[YX[Y[ZY[\X[Z\[YZY[\[][\]Z[^Z]Y[ZZZYZZ[YZY\Y\[ZW[[]\^]\Z\]^\[]ZZY[Y[ZYZ[YZZZZ\Y\\][^[\]^\[]\^\Y[ZZXZYXYZZYZYZZ\]]^Z]\]]\]\^]\^ZZYZYZZYZYZXWZ[Z]^\][\^]\[^[\^]\YWZYZY[ZYZ[Y[YZ[\[Z^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþfeffþfegfgcefþcfefefeffeffþcfgfecfefcefcdfeþfeefecffgcgffgefefgfþ
fgecfgfefcfefecefcgfeefeþfcdffececgdffgcfefgeffcfecgfþfcfffdcgefdcfecffdfgdfcgfegffegeZZcgdffefcefgcgefgfcfgefeffgec]\X[ZYfcefgffefefgcfeefefgcfec[]\][ZY[ZYffcfdfcffefefcefcffd[]^\[^ZYXZYZZZecgcegecegfgffge]\^\]\]\[Z[YX[Y[ZYfefefgdefece[][\]Z[^Z]Y[ZZZYZZ[YZYeffcffef]\^]\Z\]^\[]ZZY[Y[ZYZ[YZZZegfg\][^[\]^\[]\^\Y[ZZXZYXYZZYZYZZ\]]^Z]\]]\]\^]\^ZZYZYZZYZYZXWZ[Z]^\][\^]\[^[\^]\YWZYZY[ZYZ[Y[YZ[\[Z^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ þFþFþFfGfFþGfGeFeGþFþFfeFHfGfHfþGþFþFGefGfefgfefHþFþGfGefgHGfeFeGefþFþ
FþGeefefFGfFGfGfefFfGþ
GeGeFfGfFGeeGHFeFfgGgeþ	GeGefGeFfGHFfHfGfGgfefFfþFþZfefgHfGeHfGefeeFefFfeGefGþY[feffFeFeeeeGfFGeeGFefGgHþ[Z[egfGfGfefGefGHFfHGfeGfGfþZYXZGfeeHefFHfgHfGefHgFeGfefFþ[Z[Y[effFfgHfGefefFefeGfegGgGþY[ZZZ[eeGfeeeFfefFGfFefeffeGHeþZZY[Y[ZggeFfeGeGfGefGfFeFeGfFfeþY[ZZXZY[ffGefeFfGefeegGeGfefGefgZZYZYZZYZeeFfFGeefGFfeeGHgfGfe]\YWZYZY[ZY[fGeGefFeFGeFfHfefe\]Z]X[Y[ZWY[ZZYefeFeGfGHfGefef\]^\[]ZYYZYZZZ[Y[ZgfGfeFHfeeeG^\^\]\][YZ[YX[Y[ZXZYZfeGfGefGf\][\]\[^\]Y[ZZZYZZ[YZX[ZfeGHge]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[ZfHf^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ	þDþdeHgþEcEdGfgHþHþEþEþdEFdFdfGgfHIþFþFEeFdcdegHhgIhHfþGþ
EþdcdFddcDdcfIfGfgIgfHþGþFcdDcdeDdEcdHfgHGfgfGgfHþdDdEcDdDdEdFEeIHfIghGfHfHgGgþedcEeFdEDEeFcdFfgIghfgHGIgIhHfgfZZ[ZYZZ[ZYZ[ZZ[Z]^\]^]^]\]^]\^]^YWZYZY[ZYZ[Y[YZ[\[\^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþGþGþGþGþZZgfHfgfHIgHfgHfGfþGþX[ZYhgGgIgHIgHIGHgfHþ[ZY[ZYHhHfIgfIgHIGgfHfþHþHþZYXZYZZZGfgGHgfIgHhgfgHIþIþ[Z[YX[Y[ZYhHgHfgfIGfghIgfgþHþY[ZZZYZZ[YZYfGgfgGHgGfgfGgffþZZY[Y[ZYZ[YZZZfHfHIfHgGfHfHgGgþY[ZZXZYXYZZYZYZZGIgfIfHGIgfhHfgfZZYZYZZYZYZXWZ[Z]^\]^]^]\]^]\^]^YWZYZY[ZYZ[Y[YZ[\[\^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþGþGþGþHþZfegHghgHfgHGgIfGfþGþY[fdefFfIhfgHgfgHgfHþ[Z[efFGegfFeIhgfIHgIgGþHþHþZYXZdGHdFeGefefggIhghHfIþIþ[Z[Y[eefGfFfedFfefgfgIhgfgþHþY[ZZZ[fFHgfedFGefFfdfegfgfgIþZZY[Y[ZGfeFfeGedfGefdfFfdgFgfgþY[ZZXZY[efGFefFeFHfeegGeFfGfgHgfZZYZYZZYZfeGfFGfGfdFfeHdGgHdfe]\YWZYZY[ZY[ffeGedFeFGeFfeHefe\]Z]X[Y[ZWY[ZZYefeFeffGHfGefef\]^\[]ZYYZYZZZ[Y[ZefGFeFHfeHed^\^\]\][YZ[YX[Y[ZXZYZfHGfGefdf\][\]\[^\]Y[ZZZYZZ[YZX[ZfedHfe]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[Zfef^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ þDþDdEdDþDþEcDcEdEþEþdFdEdcDcdDþFdcdcccdEdcEDþDþDþdcEcDdDEEcdFEdEþDþEdDdcdEdEDFEDdFcFcEþDþ
FeEcdDFDcEeFEddEeDFEcEþDþdDdcdeEdEdFdDFDcDcEdFeFcþEdeEddDdcDccdcEdEdEdFedc]\þdeEccDEceEDdEcFcFDFDed[]\]þdEddEdEcdDFEeFededEdE[]^\[^þDdeFccFecdcEdFddEDdcD]\^\]\]\þEeEdDdcddeDdcdcEFEd[][\]Z[^Z]þdcdceEcecDdEDdcdDc]\^]\Z\]^\[]þcdDcEcdcDdEdFEeEc\][^[\]^\[]\^\decEdcdedEedcdFD\]]^Z]\]]\]\^]\^ZZ[ZYZZ[ZYZ[ZZ[Z]^\][\^]\[^[\^]\YWZYZY[ZYZ[Y[YZ[\[Z^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ þFþFþFfGfFþGfGefeGþFþFfeFefGfHfþGþFþFGefGfeHefGfHþFþGeGgfeHfFfFeHefþFþ
FþGfHfefFGfFGfGfefFfGþ
GeGHFfFfeGfgGHFeFfFGgeþ	eHfefGfFfFHGeHfGfGgfHfFfþFþZZgfgHgfgGfHfgefGffGffGefGþX[ZYhgGgGgefgFfGHgfHFeHGgFþ[ZY[ZYHhehfghGgHfGgfHgfHfefþZYXZYZZZGfgGeHhfghfgfhefefFfFþ[Z[YX[Y[ZYhHgefgfgGfggfgfgGeGþY[ZZZYZZ[YZYfGgfgGHgGfgfFgHfHeþZZY[Y[ZYZ[YZZZfehHfhHgGfGfegGgeþY[ZZXZYXYZZYZYZZGfgfgheGHgfhefghZZYZYZZYZYZXWZ[Z]^\]^]^]\]^]\^]^YWZYZY[ZYZ[Y[YZ[\[\^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ þFþFþFfGcdDþGfGeFceEdEþFfHFHfGEdFDFdDþFþFGefGfeHcEdEdcEDþDþ
FþGfGHfeHeFfdcEFcdFEdEþDþFþGeHeHgFGfFGfdEDdEDdFedcEþDþGefHFfFgfGHeGHFeFEcFEceEdDFEcEþeHGefGeGeFHffHgGdeFdDFDdDeEdFEccZfHfgefHfGfFeffeeddcEeEeddFedcd\Y[fefgFgefeGeGeFdeEcFdedcDedcd\][Z[fFfGfFfefFefGcdcEdcdEdEded^[^ZYXZGfHeGefFGfgHcedFDdcDcFdF]\]\[Z[Y[effHgfGfGfedcEeEddEddc\[^Z]Y[ZZZ[eeffeHeFefedDdFcdFcc\]^\[]ZZY[Y[ZgHeFfeGeGfdEcdDcde^\[]\^\Y[ZZXZY[feGefeFfdDcdcEdd]\]\^]\^ZZYZYZZYZfeFfFGFcEDdDFd]\[^[\^]\YWZYZY[ZY[fGeGHGdFEcEd]\]^\\[]Z]X[Y[ZWY[ZZYefHFecdFdF]Z[][Z]^\[]ZYYZYZZZ[Y[ZgfGFdEde\^\^^\^\]\][YZ[YX[Y[ZXZYZfHGEcd\][Z][\]\[^\]Y[ZZZYZZ[YZX[ZfHcd\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[Zfd]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿþHþGþGþGþEþDþEþZZgfIfgfIHgHfgHfcEdFEdFEcdcEdc]\X[ZYhgGgfIHfgHIGdFEcFEcFdDde[]\][ZY[ZYHhHhIghIgHEdFDdcdEdE[]^\[^ZYXZYZZZGIgGHghIFEeEDdcD]\^\]\]\[Z[YX[Y[ZYhHgHfgdeEFEe[][\]Z[^Z]Y[ZZZYZZ[YZYfGgfcdDd]\^]\Z\]^\[]ZZY[Y[ZYZ[YZZZIHEF\][^[\]^\[]\^\Y[ZZXZYXYZZYZYZZ\]]^Z]\]]\]\^]\^ZZYZYZZYZYZXWZ[Z]^\][\^]\[^[\^]\YWZYZY[ZYZ[Y[YZ[\[Z^]\]\]^\\[]Z]X[Y[ZWY[ZZYZZZ[X[\Z[\]Z[][Z]^\[]ZYYZYZZZ[Y[ZY[ZY\]\]\^\^^\^\]\][YZ[YX[Y[ZXZYZYXZ][\Z][Z][\]\[^\]Y[ZZZYZZ[YZX[ZWY\Z\[]\^]\]Z]^\[ZZZY[Y[ZYZ[YZZ[YZ[]^\[^[\]^\[]\^]Z[ZXWZYXWZZYZYZ[]\]^\]\]Z\]\^]\]ZZYZYZZYZYZXZZ[Z\^\][Z^]\[^[Z^]\Y[ZYZY[ZYZ[Y[YZZ][Z^]\]\]^\][]\[XZY[ZXY[ZZYZZZ[Y[\^[\]\[][[]]\[]ZYZZYZZZ[Y[ZY[ZX\]\]\^\^^\^\]\]^[Z[XY[Y[ZXZYZYYZ^[\]][Z][\]\[^\]Y[ZZZYZZ[YZY[Z[Y]\Z[Z\^]\]\]^\[]ZZY[Y[ZYZ[YZWZYZZ]^\[^[\]^\[]\^\ZXZZYZYXWZZYZYXZ[\]^\]\]Z\]\^]\^þYZXZZYZYZYZZ[Z\^\][\^]\[^[\^þZY[ZYZ[X[YZ[][\^]\]\Z^\]þ
Y[ZWYZZZ[Z[\^[Z]\[][þ[Y[ZY[ZY\]\]\^\^þZYZYXZ][Z]][þ[Z[Y\\\[þY[^]ÿ