þIIIIþIIJIJGHIþIIHIIHIIIIJIþIGIIIGIIHGIIGHIHþGIHJHGIIJGIHIJIIIIJIþ
IIHIIIIIIGIJIIGHIGJIHHIHþIGJIIIGIGJHIIHGIIIIIIIGIHGJIþIGIIIHGJIIIIIGIIIHIJHIGIIHJIIHJHþGJIIIHGIHGJIJIIJIGIJHJHIIIHGþHGIIJIIHIHGJHIHHIHIHGIHGþ
HIGIIIGIIHIGIIHIGIIHþHGJIHHIGIJIGIIJIþIHIHIJHIIJIGþHJIHIIGIþHJIJÿþJIJJþJIKJKGIJþGJIJIJIJJIJJþGJKJIGJIJGIJGHJIþJIIJIGJJKGKJJKIJIJKJþ
JKIGJKJIJGJIJIGIJGKJIIJIþJGHJJIGIGKHJJKGJIJKIJJGJIGKJþJGJJJHGKIJHGJIGJJHJKHJGKJIKJJIKIþGKHJJIJGIJKGKIJKJGJKIJIJJKIGþJGIJKJJIJIJKGJIIJIJKGJIGþ
JJGJHJGJJIJIJGIJGJJHþIGKGIKIGIKJKJJKIþJIJIJKHIJIGIþIJJGJJIJþIKJKÿþEþFþEþIJFJþFþEþEþFIHJEHGHHþFþFGHHJIFJEIEIHþEþEþIHIJIFIHIFIFGJIFþEþFIHJHIEHJEIHEHEIIHFIFþEþEIEIIFIIFJIFIJFJFGJJHHHHFþIGFIFIEHEJHIIHEIHEHIIIJIJGHIþIGIIHFHJFJFGIFIJFGEFJIGEIHHIJHJHþGJJHJHHEHIJGJIHJFHIJHFHIJIHHþIGIIJIJHEHGHJIHJIFIHGIGGþ
IIGIIIFIIHIGJJGIGJIHþHGJIHHIGJJIJIIJJþIHJHIJHIIJIGþHJIFIIHIþHJIJÿþEþFEþEþIHFJHþEþEþFIEIHGHIþFþEFþGIHIFIIJIEIHþEþEþFHIIIIEHEIEIFGIIFþFGHHIEJIFJFIFEHIEIHJIEþEþIHFIEJFIEHIHIHFHIFJIHHFHþFIFIJIGFIHJFIIJEIHIEHIIFEHGJIþIHIHJIGFIJEGHFIIFGIHFIEIIFJIIHJHþGJIFIHGEFIJGJEHJIGHJFJHHIIHHþIHJIJFHEIHGFHIHEIFHJGIGGþ
IIGHIFGIIHIGIFGIGIIHþHGJHHEIGJEIHIIJJþIHIFIJHFIJIGþHHIFIHFIþHJIJÿþHþGþEþGþEþEHþFEHþEþFþEþHþHEJHEGFGHEHþGþHþFþIþFFIFHJHFGEIþHþEþ	IþIJHKHGJGIKIFHIHGIFIþGþEþEþEþJIJEHJHHKHJFIEIJGHJFJþHþEþFþEHEJKFHJHIIIKGJEIIFIEGHHIþFHþGHGIFKEGHKHJEJKHKFJIGIEHIEJHGIEGHIHJGLFIELJKFJLIKIHEFGFIHEKIHHFHIHIJGKGIEJILGIHJLJIFGIGGHFKHKIHIJHJKHIHHFKHJJIIKIHJGHJHHJGHILJJKLIKJIHGIGHIHKJGLJIGHEKIHKHJJKKKþJKKJIHIHFJIGKIJKJEJFHJILIKKLþLKJIJIGKJFKIKHIFKGIKJKJLþ
LKLJHGKELHHIJGHIJLKLþLKIHKFJHIJKIIJKLþJILGKIJHLJJKþKIJJKIKKþKKLJÿþEþHþEþGþFþEþEGHþFþHGþEþGþFEHGFGFHJEHþEþFþJþHþGEGFHJHFIFHþFþGþIFIGHIHFIKIGJGHKHJIþIþGþHþJFJHGJIEIFJHKHHJHEJIJþEþFHþIHHGEIFIIEJGKIIIHJHFKJIHEHþJGIHJEIHEIGIJFKHKJEJHKHGEKEIFIþFKHJIKEHIFGFFHIKILJFKJLEIFLFJGHIGKIKHKFHGGIGFIJLJHIGLIJEIGIGJIIJHJJLIHGJHHHEGJHIKIIJKHKFHHGHIJJKJKKKJJHKHIIEHGIJLGJKJIHGIGHIJKKLKþLKKILIJHFJIJKJIKJIJIHIHIJKLLþLJKJKIGKJIHKIKIJGJIJIJKLþ
LKLJILKJIHHLFKHKJLKKþLKJIIKJIHJGLIKKLþKJJLHJIKHLJLþKKIKJJIKþJLKKÿþEþ EFþFEþGþEEFþEþFEFEþFþFEþEþGþEFFGGGþEFþEFþFEHIEGHHFEþEþFEþFGHEFGIEFIHEFGþFEþEþIEFGGFIIFEIGGFIGþEFþEFHGFEIIFGIHIIEFIGIHFEþ	FEIGGIFGGIGIJGFEIIFFIIEFGþIHIEFHIGHJEIIJGIFGGHIGGFHHJHþIHIGFEHJIJIHIEFIHIGJHEGIIGIHIGJIþHJIIIIHHGIFEJIGJIFEJIJHIIIIGþIHIIJIIIIHEFHGHHEFIJHIHHþ
IIHIIIGFEHIHFEHIHIIIþIHJIIIIHJJIEFGJJþIIIIIJIIIJIHþIJIGIIGIþIJIJÿþEþFEþGþEFþEþFEEþEFþFþJEFEFþFEþGGGFFEIIGþEþEþEFIIGEHIEFIGFEþEFþGFEGIFEIGFEIGFIEFþFEIJGGFGGIEFFJFGGFEHIGþEþHIEFIJGIFEHIJIGFFIEFGFFEþIJGFEFIFFIIEFGJIGHGGFGGGIEFIþGIHIHIFGGGIGGFGGIIFEGIGIJFEIIIGIþHHIIGHJGEKGGJIIFEIIGHGHIEFGGþGGIGJIFEFHIGJGEFHHFJIIGIþ
HIIGFEIIGIFEIGIIIGIIþJJIIEFJJGEFGIJGHþGFEIIHJIHIHIþIFIIFIJHþJIJHÿþEþFEþFþEþIHFJHþEþEþFIJIJGHIþFþEFþGIHIIIEIHþEþEþFIIIIGIFGIIFþFGIHIEIJIEIIJIEþEþEIIFIIIFHIFJIHHFHþFIFIIIEGIGIIIIHEHGJIþIGIIIEGFIJ		IEHIFJIIHJHþGJIFIHGE		

FJHIIIHHþIGIIJFE			
E
HJGIGGþ
IIGHF				
G
FIGIIHþHGJIJEJ
EIHIIJJþIHIFIJHFIJIGþHJIFIIFIþHJIJÿþEþFþEþEþHEþFEþEþFIJFJHFþEþEþFIHJEHGHHþFþFGHHJIFJEIEIHþEþEþIHIJIFIHIFIFGJIFþFIHIFIFEHIEIHJIEþ	EIEI	IHFHIFJIHHFHþIGFIFI	
EIHIEHIHIEHGJIþIGIIHFHJE	E
FGIHFIEEIFJIIHJHþGJJHJHG	F	GFIHJIGHJFJHHIIHHþIGIIJIJHEHHHJIHJIFIJGIGGþ
IIGIIIFIIHIGJJGIGIIHþHGJIHHIGJJIJIIJJþIHJHIJHIIJIGþHJIFIIFIþHJIJÿþFþEþHEþEþEþFIJFJþFþEþFIHJEHGHGþFþFGHHIHIHþEþEþIHIJJIFþEþFIHJHHFIFþEþEIEIIF	HFHFþIGFIFIEH		
EHGHIþIGIIHFHJIEE	
FJIJHJHþGJJHJHGF	F
HHIIHHþIGIIJHFE	FH
GIGGþ
IIGIIHG	F
IG
IHþHGJ	E	GJE
H
IJJþIHIFIJHFIJIGþHHIFIHFIþHJIJÿþEþEþFEþFþEþIHFJHþEþEþFIEIHGHIþFþEFþGIHIFIIIIEIHþEþEþFHIIIIEHEIEIFGIIFþFGHHIEIIFJFIFEHIEIHJIEþEþEIHFIIIFIEHIHGJIHHFHþFIFIIIIHII	IHIEHGJIþIHIHIEG	IFIE	
EHIFJIIHJHþGJIFIE
EJGJGE	F
FJHHIIHHþIHIIJFHEIHGI	FEGFHJGIGGþ
IIGHIFGIIHIGHFJIGIIHþHGJHHEIGJEIHIIJJþIHIFIJHFIJIGþHHIFIHFIþHJIJÿþEþFþEþHEþEþEþFIJFJþFþEþEþFIHJEHGHHþFþFGHHEIEIHþEþEþIHIJIFIFGJIFþEþFIHJHIEI	HEHEIIHFIFþEþEIEIIFIIFHJIJJFJFGJJHHHHFþIGFIFIEHEJHIHHJIHEHIIIJIJGHIþIGIIHFHJFJFHGEFJIGEIHHIJHJHþGJJHJHHEH	FHIJHFHIJIHHþIGIIJIJ	HJIFIHGIGGþ
IIGII	EJJGIGJIHþHGJIFE

FIJIIJJþIHIHFJIHIJIGþHJHFIIFIþIJIJÿþEþEþFEþFþEþIHFJHþEþEþFIEIHGHIþFþEFþGIHIHþEþEþFHII	GIIFþFGHHI	
IEIHJIEþEþEIHFII		EIFJIHHFHþFIFIIIH			
EEHIIJEHGJIþIHIHIEG		

EFJFIEHIFJIIHJHþGJIFIE	
EEFHGHJFJHHIIHHþIHIIJFE
FJFIHHIFHJGIGGþ
IIGHIFGIHHIGIFGIGIIHþHGJHHEIGJEIHIIJJþIHIFIJHFIJIGþHHIFIHFIþHJIJÿþEþFþEþHEþEþEþFIJFJþFþEþEþFIHJEHGHHþFþFGHHIHþEþEþIHIJIFþEþFIHJ	

IFþEþEIEII			

HHFþIGFIFI			E

JGHIþIGIIHFHJE			
	
EEHIJHJHþGJJHJHFEE		E


FGIJIHHþIGHIHGEF	E
EFGIHGGGþ
IIJHFGFF	FGFGIHHIHþHGJIHHGGGIFGIIJJþIHFEIJHIIJIGþHJIFIIFIþHJIJÿþEþFþEþHEþEþEþFIJFJþFþEþEþFIHJEHGHHþFþEFþGHHJIFJEIEIHþEþEþFHIIJIFIHIFIFGJIFþEþ
FGHHIEIIJIIIHFIFþEþEþEIHFIIIFEIGJJHHHHFþFIFIIIEGI	FJIIIJIJGHIþIHIHIEGFIJE	EHHIGEIHHIJHJHþGJIFIHGHGG	
E
FJIJHFHIJIHHþIHIIJIJHEF
GG
HJIFIHGIGGþ
IIGIIIFIFHIGIFGIGIIHþHGJIHHIGJEIHIIJJþIHJHIJHFIJIGþHJIFIHFIþHJIJÿþEþFþEþHEþEþEþFIJFJþFþEþEþFIHJEHGHHþFþFGHHJIFJEIEIHþEþEþIHIJIFIHIFIFGJIFþEþGIJEIHEHEIIHFIFþEþEIIFIJFHHHIHFþIGF		HEIHIJGHIþIGIIHE	F
JFGE		HIJHJHþGJJHFGE	
G
IHJFE

JIHHþIGHIJFHEIHGHJIHHE	F
IGGþ
JIGHIFGIIHIGJIGFGHIHþHGJHHEIGJEIJIHJIþIHIFIJHFIJIJþHHIFIHFIþHJIJÿþ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYXZWZ\[Y[þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[YZWYYZZW[\[ZW\Z[\YY\Z[ZY\[þYZ\\[[Z[Y\ZY[\Z\[[X\[Z\W\[\[[Y\[þ[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\þ[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\þ
YX\Z\[[ZWZ\[ZY[[[\Y\þ\\X[YY\\Z[X[W\[Yþ[\X[Z\[YZY[\þ\Y\[ZW[[þZ\Y\ÿþIIIIþIIJIJJHIþIIHIIJIIJJJIþIJIJIHJIJJJIIHIHþGIJJJKJJJKKKKJJIIIJIþ
IIHJIJKJKKJJKLKKJJJIJHIHþIGJIJKJJKKLLKKLMLKKKJJIIHGJIþIGIIIHJJKKMLLMMLMMMLLKKKJJJIIHJHþGJIIIJJJKJKLLLKLLKKKJJJIIIHGþHGIIJIJJIKKLKJKJJHIJHIHGþ
HIHIIIJJJKKJJIHJHIJHþHGJIHJJJKKJJJIJJþIHIHJJJJIJIHþHJIHIIHIþHJIJÿþ]YZ\þZ^_^\]^\þ\Z^___^^^^^_þ_____^_^]^^]^__^þ_^^__^^^^^]]]]^^_^^_þ
[\_^^^^^]]_]^\_^]^^__]]\þ\[^___^]]]]^][]]\]^]^^^^_]\[þYZ\^___^^^]\]^]_]]Z^]]]^^_\[[Y\[þ[Y^___^]]\[]]Z^^\[\\]^]\Y\[\þ[Y__^^]]\]\]]\]_][^^^^^\þ
YZ^^^]]\Y]^]\[\]]^]^þ\^^^][^^\\\\]]^]þ_^^]\\[YZY[\þ^^\[ZZ[[þZ\Y\ÿ