þHHHHþHHIHIFGHþHHGHHGHHHHIHþHFHHHFHHGFHHFGHGþFHGIGFHHIFHGHIHHHHIHþ
HHGHHHHHHFHIHHFGHFIHGGHGþHFIHHHFHFIGHHGFHHHHHHHFHGFIHþHFHHHGFIHHHHHFHHHGHIGHFHHGIHHGIGþFIHHHGFHGFIHIHHIHFHIGIGHHHGFþGFHHIHHGHGFIGHGGHGHGFHGFþ
GHFHHHFHHGHFHHGHFHHGþGFIHGGHFHIHFHHIHþHGHGHIGHHIHFþGIHGHHFHþGIHIÿþIHIIþIHJIJFHIþFIHIHIHIIHIIþFIJIHFIHIFHIFGIHþIHHIHFIIJFJIIJHIHIJIþ
IJHFIJIHIFIHIHFHIFJIHHIHþIFGIIHFHFJGIIJFIHIJHIIFIHFJIþIFIIIGFJHIGFIHFIIGIJGIFJIHJIIHJHþFJGIIHIFHIJFJHIJIFIJHIHIIJHFþIFHIJIIHIHIJFIHHIHIJFIHFþ
IIFIGIFIIHIHIFHIFIIGþHFJFHJHFHJIJIIJHþIHIHIJGHIHFHþHIIFIIHIþHJIJÿþDþEþCþHIEIþEþDþDþEHGICGFGGþEþEFGGIHEIDHCHGþDþDþHGHIHEHGHEHEFIHEþDþEHGIGHCGIDHGCGCHHGEHEþDþDHCHHEHHEIHEHIEIEFIIGGGGEþHFEHEHDGDIGHHGCHGCGHHHIHIFGHþHFHHGEGIEIEFHEHIEFDEIHFDHGGHIGIGþFIIGIGGDGHIFIHGIEGHIGEGHIHGGþHFHHIHIGDGFGIHGIHEHGFHFFþ
HHFHHHEHHGHFIIFHFIHGþGFIHGGHFIIHIHHIIþHGIGHIGHHIHFþGIHEHHGHþGIHIÿþDþEDþDþHGEIGþDþDþEHCHGFGHþEþDEþFHGHEHHIHCHGþDþDþEGHHHHDGCHDHEFHHEþEFGGHDIHEIEHECGHDHGIHDþDþHGEHDIEHCGHGHGEGHEIHGGEGþEHEHIHFEHGIEHHICHGHCGHHEDGFIHþHGHGIHFEHICFGEHHEFHGEHDHHEIHHGIGþFIHEHGFDEHIFIDGIHFGIEIGGHHGGþHGIHIEGDHGFEGHGDHEGIFHFFþ
HHFGHEFHHGHFHEFHFHHGþGFIGGDHFIDHGHHIIþHGHEHIGEHIHFþGGHEHGEHþGIHIÿþGþFþDþFþCþDGþECGþDþEþDþGþGDIGDFEFGDGþFþGþEþHþEEHEGIGEFDHþGþDþ	HþHIGJGFIFHJHEGHGFHEHþFþCþDþCþIHIDGIGGJGIEHCHIFGIEIþGþDþEþDGDIJEGIGHHHJFIDHHEHCFGGHþEGþFGFHEJDFGJGIDIJGJEIHFHDGHCIGFHDFGHGIFKEHCKIJEIKHJHGDEFEHGDJHGGEGHGHIFJFHDIHKFHGIKIHEFHFFGEJGJHGHIGIJGHGGEJGIIHHJHGIFGIGGIFGHKIIJKHJIHGFHFGHGJIFKIHFGDJHGJGIIJJJþIJJIHGHGEIHFJHIJIDIEGIHKHJJKþKJIHIHFJIEJHJGHEJFHJIJIKþ
KJKIGFJDKGGHIFGHIKJKþKJHGJEIGHIJHHIJKþIHKFJHIGKIIJþJHIIJHJJþJJKIÿþDþGþCþFþEþDþDFGþEþGFþCþFþEDGFEFEGIDGþDþEþIþGþFDFEGIGEHEGþEþFþHEHFGHGEHJHFIFGJGIHþHþFþGþIEIGFIHCHEIGJGGIGDIHIþCþEGþHGGFCHEHHDIFJHHHGIGEJIHGDGþIFHGICHGDHFHIEJGJIDIGJGFDJDHEHþEJGIHJDGHEFEEGHJHKIEJIKCHEKEIFGHFJHJGJEGFFHFEHIKIGHFKHIDHFHFIHHIGIIKHGFIGGGCFIGHJHHIJGJEGGFGHIIJIJJJIIGJGHHDGFHIKFIJIHGFHFGHIJJKJþKJJHKHIGEIHIJIHJIHIHGHGHIJKKþKIJIJHFJIHGJHJHIFIHIHIJKþ
KJKIHKJIHGGKEJGJIKJJþKJIHHJIHGIFKHJJKþJIIKGIHJGKIKþJJHJIIHJþIKJJÿþCþ CEþEDþFþCDEþCþECEDþEþECþCþFþDEEFFFþDEþCEþEDGHCFGGEDþCþEDþEFGDEFHCEHGDEFþECþCþHDEFFEHHEDHFFEHFþDEþCEGFEDHHEFIGHHDEHFHGEDþ	EDHFFHEFFHFHIFEDHHEEHHDEFþHGHDEGHFGICHHIFHEFFGHFFEGGIGþHGHFEDGIHIHGHCEHGHFIGCFHHFHGHFIHþGIHIHHGGFHEDIHFIHECIHIGHIHHFþHGHHIIHIHGDEGFGGDEHIGHGGþ
HHGHHHFEDGHGEDGHGHHHþHGIHIIHGIIHDEFIIþHHHHHIHHHIHGþHIHFHHFHþHIHIÿþCþECþFþDEþCþEDCþCEþEþIDECEþEDþFFFEEDHHFþCþCþDEIHFCGHDEHFECþCEþFEDFHECHFEDHFEHDEþEDHIFFEFFHDEEIEFFEDGHFþCþGHDEHIFHEDGHIHFEEHDEFEECþHIFEDEHEEHHDEFHHFGFFEFFFHDEHþFHGHGHEFFFHFFEFFHIECFHFHIEDHIHFHþGGHIFGIFCHFFIHHECHHFGFGHDEFFþFFHFIHECEGHFIFDEGGEIHIFHþ
GHHFEDHHFHEDHFHHHFHHþIIHHDEIIFDEFHIFGþFEDHHGIHGHGHþHEHHEHIGþIHIGÿþDþEDþEþDþHGEIGþDþDþEHIHIFGHþEþDEþFHGHHHCHGþDþDþEHHHIFHEFHHEþEFHGHDHIHDHHIHDþDþDHHEHHIEGHEIHGGEGþEHEHIHDFHFIHHHGDGFIHþHFHHHDFEHIC		ICGHEIHHGIGþFIHEHGFD		

EIGIHHGGþHFIHIED			
D
GIFHFFþ
HHFGE				
F
EIFHHGþGFIHIDI
DHGIHIIþHGHEHIGEHIHFþGIHEHHEHþGIHIÿþDþEþDþDþGDþECþCþEHIEIGEþDþDþEHGICGFGGþEþEFGGIHEIDHCHGþDþDþHGHIHEHGHEHEFIHEþEHGHEHECGHDHGIHDþ	DHCH	HGEGHEIHGGEGþHFEHEH	
CHGHCGHGHDGFIHþHFHHGEGIC	C
EFHGEHDCHEIHHGIGþFIIGIGF	E	FEHGIHFGIEIGGHHGGþHFHHIHIGDGGGIHGIHEHIFHFFþ
HHFHHHEHHGHFIIFHFHHGþGFIHGGHFIIHIHHIIþHGIGHIGHHIHFþGIHEHHEHþGIHIÿþEþDþGDþCþCþEHIEIþEþDþEHGICGFGFþEþEFGGHGHGþDþDþHGHIIHEþDþEHGIGGEHEþDþDHCHHE	GEGEþHFEHEHDG		
DGFGHþHFHHGEGIHCD	
EIHIGIGþFIIGIGFE	E
IGHHGGþHFHHIGED	EG
FHFFþ
HHFHHGF	E
HF
HGþGFI	D	FID
G
HIIþHGHEHIGEHIHFþGGHEHGEHþGIHIÿþDþDþEDþEþDþHGEIGþDþDþEHCHGFGHþEþDEþFHGHEHHHHCHGþDþDþEGHHIHDGCHDHEFHHEþEFGGHDHHEIEHECGHDHGIHDþDþDHGEIHHEHDGHGFIHGGEGþEHEIHHHGHI	HGHDGFIHþHGHGHDF	HEHD	
DGHEIHHGIGþFIHEHD
DIFIFD	E
EIGGHHGGþHGHHIEGDHGFH	EDFEGIFHFFþ
HHFGHEFHHGHFGEIHFHHGþGFIGGDHFIDHGHHIIþHGHEHIGEHIHFþGGHEHGEHþGIHIÿþDþEþDþGDþCþCþEHIEIþEþDþDþEHGICGFGGþEþEFGGDHCHGþDþDþHGHIHEHEFIHEþDþEHGIGHCH	GCGCHHGEHEþDþDHCHHEHHEGIHIIEIEFIIGGGGEþHFEHEHDGDIGHGGIHGCGHHHIHIFGHþHFHHGEGIEIEGFDEIHFDHGGHIGIGþFIIGIGGDG	EGHIGEGHIHGGþHFHHIHI	GIHEHGFHFFþ
HHFHH	CIIFHFIHGþGFIHEC

EHIHHIIþHGHGEIHGHIHFþGIGEHHEHþHIHIÿþDþDþEDþEþDþHGEIGþDþDþEHCHGFGHþEþDEþFHGHGþDþDþEGHH	FHHEþEFGGH	
HDHGIHDþDþDHGEHH		CHEIHGGEGþEHEHHHG			
DCGHHIDGFIHþHGHGHDF		

DEIEHDGHEIHHGIGþFIHEHD	
DDEGFGIEIGGHHGGþHGHHIED
EIEHGGHEGIFHFFþ
HHFGHEFHGGHFHEFHFHHGþGFIGGDHFIDHGHHIIþHGHEHIGEHIHFþGGHEHGEHþGIHIÿþDþEþDþGDþCþCþEHIEIþEþDþDþEHGICGFGGþEþEFGGHGþDþDþHGHIHEþDþEHGI	

HEþDþDHCIH			

GGEþHFEHEH			C

IFGHþHFHHGEGIC			
	
DDGHIGIGþFIIGIGEDD		C


EFHIHGGþHFGHGFDE	D
DEFHGFFFþ
HHIGEFEE	EFEFHGGHGþGFIHGHFFFHEFHHIIþHGEDHIGHHIHFþGIHEHHEHþGIHIÿþDþEþDþGDþCþCþEHIEIþEþDþDþEHGICGFGGþEþDEþFGGIHEIDHCHGþDþDþEGHHIHEHGHEHEFIHEþDþ
EFGGHDHHIHHHGEHEþDþDþDHGEHHHEDHFIIGGGGEþEHEIHHDFH	EIHHHIHIFGHþHGHGHDFEHID	CGGHFDHGGHIGIGþFIHEHGFGFF	
D
EIHIGEGHIHGGþHGHHIHIGDE
FF
GIHEHGFHFFþ
HIFHHHEHEGHFHEFHFHHGþGFIHGGHFIDHGHHIIþHGIGHIGEHIHFþGIHEHGEHþGIHIÿþDþEþDþGDþCþCþEHIEIþEþDþDþEHGICGFGGþEþEFGGIHEIDHCHGþDþDþHGHIHEHGHEHEFIHEþDþFHIDHGCGCHHGEHEþDþDHHEHIEGGGHGEþHFE		GCHGHIFGHþHFHHGC	E
IEFD		GHIGIGþFIIGEFD	
F
HGIED

IHGGþHFGHIEGDHGFGIHGGD	E
HFFþ
IHFGHEFHHGHFIHFEFGHGþGFIGGDHFIDHIHGIHþHGHEHIGEHIHIþGGHEHGEHþGIHIÿþ[YZ\þZ\[Y\[Y\þ\ZZW\[Z\[ZY[þ\YY\Z\ZYYZWZ\[Y\þ[\X\[Y\Y[\[\Y[[\[\ZYþ
[[\[\\X[YW\Y\Z\\Y\Z[\YX\þ\[Y[WYYZZW[\[Y[\Z[\YY\Z[ZY\[þYZ\\[[[[Y\ZY[\[\[[X\[Z\Z\[\[[Y\[þ[YZ\[W\Y[ZY[[X\\ZYZZY[Z\XW[\þ[Y[\\\YYZ[Z[[Z[\[Y[Z[YY\þ
YX\Z\[[ZWZ\[ZY[[[\Y\þ\\X[YY\\Z[W[W\[Yþ[\X[Z\[YZW[\þ\Y\[ZW[[þZ\Y\ÿþHHHHþHHIHIIGHþHHGHHIHHIIIHþHIHIHGIHIIIHHGHGþFHIIIJIIIJJJJIIHHHIHþ
HHGIHIJIJJIIJKJJIIIHIGHGþHFIHIJIIJJKKJJKLKJJJIIHHGFIHþHFHHHGIIJJLKKLLKLLLKKJJJIIIHHGIGþFIHHHIIIJIJKKKJKKJJJIIIHHHGFþGFHHIHIIHJJKJIJIIGHIGHGFþ
GHGHHHIIIJJIIHGIGHIGþGFIHGIIIJJIIIHIIþHGHGIIIIHIHGþGIHGHHGHþGIHIÿþ]YZ\þZ^_^\]^\þ\Z^___^^^^^_þ_____^_^]^^]^__^þ_^^__^^^^^]]]]^^_^^_þ
[\_^^^^^]]_]^\_^]^^__]]\þ\[^___^]]]]^][]]\]^]^^^^_]\[þYZ\^___^^^]\]^]_]]Z^]]]^^_\[[Y\[þ[Y^___^]]\[]]Z^^\[\\]^]\Y\[\þ[Y__^^]]\]\]]\]_][^^^^^\þ
YZ^^^]]\Y]^]\[\]]^]^þ\^^^][^^\\\\]]^]þ_^^]\\[YZY[\þ^^\[ZZ[[þZ\Y\ÿ